import type { RevelationEntry } from "../../schema";

/**
 * Theme: Creation (الخلق)
 *
 * Signs in the natural world, the design of the cosmos,
 * and the invitation to observe.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const creationCollection: RevelationEntry[] = [
  {
    id: "q:67:3-4",
    type: "quran",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ ۝ ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًا وَهُوَ حَسِيرٌ",
    english: "He who created seven heavens in layers. You do not see any flaw in the creation of the Most Merciful. So look again — do you see any defect? Then look again twice more — your sight will return to you humbled and worn out.",
    source: "Al-Mulk 67:3–4",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:71:15-16",
    type: "quran",
    arabic: "أَلَمْ تَرَوْا۟ كَيْفَ خَلَقَ ٱللَّهُ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۝ وَجَعَلَ ٱلْقَمَرَ فِيهِنَّ نُورًا وَجَعَلَ ٱلشَّمْسَ سِرَاجًا",
    english: "Do you not see how Allah created seven heavens in layers, and placed the moon as a light in them and made the sun a lamp?",
    source: "Nūḥ 71:15–16",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:21:30",
    type: "quran",
    arabic: "أَوَلَمْ يَرَ ٱلَّذِينَ كَفَرُوٓا۟ أَنَّ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضَ كَانَتَا رَتْقًا فَفَتَقْنَـٰهُمَا ۖ وَجَعَلْنَا مِنَ ٱلْمَآءِ كُلَّ شَىْءٍ حَىٍّ ۖ أَفَلَا يُؤْمِنُونَ",
    english: "Have the disbelievers not considered that the heavens and the earth were joined together, then We split them apart? And We made from water every living thing. Will they not then believe?",
    source: "Al-Anbiyāʼ 21:30",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:36:36",
    type: "quran",
    arabic: "سُبْحَـٰنَ ٱلَّذِى خَلَقَ ٱلْأَزْوَٰجَ كُلَّهَا مِمَّا تُنۢبِتُ ٱلْأَرْضُ وَمِنْ أَنفُسِهِمْ وَمِمَّا لَا يَعْلَمُونَ",
    english: "Glory be to the One who created all pairs — of what the earth produces, of themselves, and of what they do not know.",
    source: "Yā Sīn 36:36",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "q:41:53",
    type: "quran",
    arabic: "سَنُرِيهِمْ ءَايَـٰتِنَا فِى ٱلْـَٔافَاقِ وَفِىٓ أَنفُسِهِمْ حَتَّىٰ يَتَبَيَّنَ لَهُمْ أَنَّهُ ٱلْحَقُّ",
    english: "We will show them Our signs in the horizons and within themselves until it becomes clear to them that it is the truth.",
    source: "Fuṣṣilat 41:53",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:78:6-16",
    type: "quran",
    arabic: "أَلَمْ نَجْعَلِ ٱلْأَرْضَ مِهَـٰدًا ۝ وَٱلْجِبَالَ أَوْتَادًا ۝ وَخَلَقْنَـٰكُمْ أَزْوَٰجًا ۝ وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا ۝ وَجَعَلْنَا ٱلَّيْلَ لِبَاسًا ۝ وَجَعَلْنَا ٱلنَّهَارَ مَعَاشًا",
    english: "Have We not made the earth a resting place, and the mountains as stakes? And We created you in pairs, and made your sleep a rest, and made the night a covering, and made the day for livelihood.",
    source: "Al-Nabaʼ 78:6–11",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "q:24:45",
    type: "quran",
    arabic: "وَٱللَّهُ خَلَقَ كُلَّ دَآبَّةٍ مِّن مَّآءٍ ۖ فَمِنْهُم مَّن يَمْشِى عَلَىٰ بَطْنِهِۦ وَمِنْهُم مَّن يَمْشِى عَلَىٰ رِجْلَيْنِ وَمِنْهُم مَّن يَمْشِى عَلَىٰٓ أَرْبَعٍ ۚ يَخْلُقُ ٱللَّهُ مَا يَشَآءُ",
    english: "Allah has created every creature from water. Some of them crawl on their bellies, some walk on two legs, and some walk on four. Allah creates what He wills.",
    source: "Al-Nūr 24:45",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "q:31:10",
    type: "quran",
    arabic: "خَلَقَ ٱلسَّمَـٰوَٰتِ بِغَيْرِ عَمَدٍ تَرَوْنَهَا ۖ وَأَلْقَىٰ فِى ٱلْأَرْضِ رَوَٰسِىَ أَن تَمِيدَ بِكُمْ وَبَثَّ فِيهَا مِن كُلِّ دَآبَّةٍ",
    english: "He created the heavens without pillars that you can see, and placed firm mountains on earth so it does not shake with you, and scattered all kinds of creatures throughout.",
    source: "Luqmān 31:10",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "q:16:66",
    type: "quran",
    arabic: "وَإِنَّ لَكُمْ فِى ٱلْأَنْعَـٰمِ لَعِبْرَةً ۖ نُّسْقِيكُم مِّمَّا فِى بُطُونِهِۦ مِنۢ بَيْنِ فَرْثٍ وَدَمٍ لَّبَنًا خَالِصًا سَآئِغًا لِّلشَّـٰرِبِينَ",
    english: "And in livestock there is a lesson for you. We give you drink from what is in their bellies — between excretion and blood — pure milk, palatable to drinkers.",
    source: "Al-Naḥl 16:66",
    category: "creation",
    themes: ["reflection", "provision"],
    editorialStatus: "published",
  },
  {
    id: "q:86:5-7",
    type: "quran",
    arabic: "فَلْيَنظُرِ ٱلْإِنسَـٰنُ مِمَّ خُلِقَ ۝ خُلِقَ مِن مَّآءٍ دَافِقٍ ۝ يَخْرُجُ مِنۢ بَيْنِ ٱلصُّلْبِ وَٱلتَّرَآئِبِ",
    english: "So let man consider from what he was created. He was created from a gushing fluid, emerging from between the backbone and the ribs.",
    source: "Al-Ṭāriq 86:5–7",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:22:5",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلنَّاسُ إِن كُنتُمْ فِى رَيْبٍ مِّنَ ٱلْبَعْثِ فَإِنَّا خَلَقْنَـٰكُم مِّن تُرَابٍ ثُمَّ مِن نُّطْفَةٍ ثُمَّ مِنْ عَلَقَةٍ ثُمَّ مِن مُّضْغَةٍ",
    english: "O people, if you are in doubt about the Resurrection, then consider that We created you from dust, then from a drop of fluid, then from a clinging clot, then from a lump of flesh.",
    source: "Al-Ḥajj 22:5",
    category: "creation",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:39:21",
    type: "quran",
    arabic: "أَلَمْ تَرَ أَنَّ ٱللَّهَ أَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَسَلَكَهُۥ يَنَـٰبِيعَ فِى ٱلْأَرْضِ ثُمَّ يُخْرِجُ بِهِۦ زَرْعًا مُّخْتَلِفًا أَلْوَٰنُهُۥ",
    english: "Do you not see that Allah sends down water from the sky, then channels it into springs in the earth, then produces with it crops of varying colours?",
    source: "Al-Zumar 39:21",
    category: "creation",
    themes: ["provision"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Creation ═══

  {
    id: "h:muslim:2643",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ",
    english: "Allah is beautiful and He loves beauty.",
    source: "Ṣaḥīḥ Muslim 91",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:3321",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَىْءٍ",
    english: "Allah has prescribed excellence in all things.",
    source: "Ṣaḥīḥ Muslim 1955",
    category: "creation",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:2363",
    type: "hadith",
    arabic: "مَا مِنْ مُسْلِمٍ يَغْرِسُ غَرْسًا أَوْ يَزْرَعُ زَرْعًا فَيَأْكُلُ مِنْهُ طَيْرٌ أَوْ إِنْسَانٌ أَوْ بَهِيمَةٌ إِلاَّ كَانَ لَهُ بِهِ صَدَقَةٌ",
    english: "No Muslim plants a tree or sows a seed from which a bird, a person, or an animal eats — except that it is counted as charity for him.",
    source: "Ṣaḥīḥ al-Bukhārī 2320",
    category: "creation",
    themes: ["provision"],
    editorialStatus: "published",
  },
];
