import type { RevelationEntry } from "../../schema";

/**
 * Theme: Gratitude (الشكر)
 *
 * Thankfulness to Allah, acknowledgement of blessings,
 * and the relationship between gratitude and increase.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const gratitudeCollection: RevelationEntry[] = [
  {
    id: "q:14:7",
    type: "quran",
    arabic: "وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ ۖ وَلَئِن كَفَرْتُمْ إِنَّ عَذَابِى لَشَدِيدٌ",
    english: "And remember when your Lord proclaimed: if you are grateful, I will certainly give you more. But if you are ungrateful, surely My punishment is severe.",
    source: "Ibrāhīm 14:7",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "q:31:12",
    type: "quran",
    arabic: "وَلَقَدْ ءَاتَيْنَا لُقْمَـٰنَ ٱلْحِكْمَةَ أَنِ ٱشْكُرْ لِلَّهِ ۚ وَمَن يَشْكُرْ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِۦ",
    english: "We blessed Luqmān with wisdom, saying: be grateful to Allah — for whoever is grateful, it is only for their own good.",
    source: "Luqmān 31:12",
    category: "gratitude",
    themes: ["knowledge"],
    editorialStatus: "published",
  },
  {
    id: "q:2:152",
    type: "quran",
    arabic: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ وَٱشْكُرُوا۟ لِى وَلَا تَكْفُرُونِ",
    english: "So remember Me, and I will remember you. Be grateful to Me, and never deny Me.",
    source: "Al-Baqarah 2:152",
    category: "gratitude",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:27:40",
    type: "quran",
    arabic: "هَـٰذَا مِن فَضْلِ رَبِّى لِيَبْلُوَنِىٓ ءَأَشْكُرُ أَمْ أَكْفُرُ ۖ وَمَن شَكَرَ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِۦ",
    english: "This is by the grace of my Lord, to test me whether I am grateful or ungrateful. And whoever is grateful, it is for their own good.",
    source: "Al-Naml 27:40",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "q:34:13",
    type: "quran",
    arabic: "ٱعْمَلُوٓا۟ ءَالَ دَاوُۥدَ شُكْرًا ۚ وَقَلِيلٌ مِّنْ عِبَادِىَ ٱلشَّكُورُ",
    english: "Work, O family of Dāwūd, in gratitude. And few of My servants are truly grateful.",
    source: "Sabaʼ 34:13",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "q:16:18",
    type: "quran",
    arabic: "وَإِن تَعُدُّوا۟ نِعْمَةَ ٱللَّهِ لَا تُحْصُوهَآ ۗ إِنَّ ٱللَّهَ لَغَفُورٌ رَّحِيمٌ",
    english: "If you tried to count Allah's blessings, you could never enumerate them. Indeed, Allah is All-Forgiving, Most Merciful.",
    source: "Al-Naḥl 16:18",
    category: "gratitude",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:14:34",
    type: "quran",
    arabic: "وَءَاتَىٰكُم مِّن كُلِّ مَا سَأَلْتُمُوهُ ۚ وَإِن تَعُدُّوا۟ نِعْمَتَ ٱللَّهِ لَا تُحْصُوهَآ",
    english: "He has given you all that you asked for. And if you tried to count Allah's blessings, you could never enumerate them.",
    source: "Ibrāhīm 14:34",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "q:93:11",
    type: "quran",
    arabic: "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ",
    english: "And proclaim the blessings of your Lord.",
    source: "Al-Ḍuḥā 93:11",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "q:93:6-8",
    type: "quran",
    arabic: "أَلَمْ يَجِدْكَ يَتِيمًا فَـَٔاوَىٰ ۝ وَوَجَدَكَ ضَآلًّا فَهَدَىٰ ۝ وَوَجَدَكَ عَآئِلًا فَأَغْنَىٰ",
    english: "Did He not find you an orphan and give you shelter? Did He not find you lost and guide you? Did He not find you in need and make you self-sufficient?",
    source: "Al-Ḍuḥā 93:6–8",
    category: "gratitude",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:55:13",
    type: "quran",
    arabic: "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
    english: "Then which of your Lord's favours will you both deny?",
    source: "Al-Raḥmān 55:13",
    category: "gratitude",
    themes: ["reflection"],
    editorialStatus: "published",
    scholarNotes: "This refrain appears 31 times in Sūrat al-Raḥmān.",
  },
  {
    id: "q:16:78",
    type: "quran",
    arabic: "وَٱللَّهُ أَخْرَجَكُم مِّنۢ بُطُونِ أُمَّهَـٰتِكُمْ لَا تَعْلَمُونَ شَيْـًٔا وَجَعَلَ لَكُمُ ٱلسَّمْعَ وَٱلْأَبْصَـٰرَ وَٱلْأَفْـِٔدَةَ ۙ لَعَلَّكُمْ تَشْكُرُونَ",
    english: "And Allah brought you out of the wombs of your mothers knowing nothing, and gave you hearing, sight, and intellect, so that you may be grateful.",
    source: "Al-Naḥl 16:78",
    category: "gratitude",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:46:15",
    type: "quran",
    arabic: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِىٓ أَنْعَمْتَ عَلَىَّ وَعَلَىٰ وَٰلِدَىَّ وَأَنْ أَعْمَلَ صَـٰلِحًا تَرْضَىٰهُ",
    english: "My Lord, inspire me to be grateful for Your blessings which You bestowed upon me and upon my parents, and to do good deeds that please You.",
    source: "Al-Aḥqāf 46:15",
    category: "gratitude",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:7:10",
    type: "quran",
    arabic: "وَلَقَدْ مَكَّنَّـٰكُمْ فِى ٱلْأَرْضِ وَجَعَلْنَا لَكُمْ فِيهَا مَعَـٰيِشَ ۗ قَلِيلًا مَّا تَشْكُرُونَ",
    english: "We have established you on earth and provided for you a means of livelihood. Yet you are seldom grateful.",
    source: "Al-Aʿrāf 7:10",
    category: "gratitude",
    editorialStatus: "published",
  },

  // ═══ Hadith — Gratitude ═══

  {
    id: "h:abu-dawud:4811",
    type: "hadith",
    arabic: "لَا يَشْكُرُ اللَّهَ مَنْ لَا يَشْكُرُ النَّاسَ",
    english: "He who does not thank people has not thanked Allah.",
    source: "Sunan Abī Dāwūd 4811 · Graded Ṣaḥīḥ",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2963",
    type: "hadith",
    arabic: "انْظُرُوا إِلَى مَنْ أَسْفَلَ مِنْكُمْ وَلاَ تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ فَهُوَ أَجْدَرُ أَنْ لاَ تَزْدَرُوا نِعْمَةَ اللَّهِ عَلَيْكُمْ",
    english: "Look at those below you and do not look at those above you, for it is more likely that you will not belittle the blessings of Allah upon you.",
    source: "Ṣaḥīḥ Muslim 2963",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:3383",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ لَيَرْضَى عَنِ الْعَبْدِ أَنْ يَأْكُلَ الأَكْلَةَ فَيَحْمَدَهُ عَلَيْهَا أَوْ يَشْرَبَ الشَّرْبَةَ فَيَحْمَدَهُ عَلَيْهَا",
    english: "Allah is pleased with the servant who eats something and praises Him for it, or drinks something and praises Him for it.",
    source: "Ṣaḥīḥ Muslim 2734",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6502",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ قَالَ مَنْ عَادَى لِي وَلِيًّا فَقَدْ آذَنْتُهُ بِالْحَرْبِ وَمَا تَقَرَّبَ إِلَىَّ عَبْدِي بِشَىْءٍ أَحَبَّ إِلَىَّ مِمَّا افْتَرَضْتُ عَلَيْهِ",
    english: "Allah said: 'Whoever shows hostility to a devoted servant of Mine, I declare war against him. My servant draws near to Me with nothing more beloved to Me than what I have made obligatory upon him.'",
    source: "Ṣaḥīḥ al-Bukhārī 6502",
    category: "gratitude",
    themes: ["supplication"],
    editorialStatus: "published",
    scholarNotes: "A ḥadīth qudsī on drawing near to Allah through obligatory and voluntary worship.",
  },
  {
    id: "h:bukhari:6478",
    type: "hadith",
    arabic: "مَنْ لاَ يَشْكُرِ الْقَلِيلَ لاَ يَشْكُرِ الْكَثِيرَ",
    english: "He who is not grateful for the little will not be grateful for the much.",
    source: "Musnad Aḥmad · Graded Ḥasan",
    category: "gratitude",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6436",
    type: "hadith",
    arabic: "لَوْ كَانَ لاِبْنِ آدَمَ وَادِيَانِ مِنْ مَالٍ لاَبْتَغَى ثَالِثًا وَلاَ يَمْلأُ جَوْفَ ابْنِ آدَمَ إِلاَّ التُّرَابُ وَيَتُوبُ اللَّهُ عَلَى مَنْ تَابَ",
    english: "If the son of Ādam had two valleys of wealth, he would seek a third. Nothing fills the belly of the son of Ādam except dust. And Allah accepts the repentance of whoever repents.",
    source: "Ṣaḥīḥ al-Bukhārī 6436",
    category: "gratitude",
    themes: ["reflection"],
    editorialStatus: "published",
  },
];
