import type { RevelationEntry } from "../../schema";

/**
 * Theme: Healing (الشفاء)
 *
 * The six Āyāt al-Shifā', Prophetic medicine,
 * and supplications for the sick.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const healingCollection: RevelationEntry[] = [
  // ═══ Qur'anic — The Six Āyāt al-Shifā' ═══

  {
    id: "q:9:14",
    type: "quran",
    arabic: "وَيَشْفِ صُدُورَ قَوْمٍ مُّؤْمِنِينَ",
    english: "And He will heal the hearts of a believing people.",
    source: "Al-Tawbah 9:14",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "q:10:57",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلنَّاسُ قَدْ جَآءَتْكُم مَّوْعِظَةٌ مِّن رَّبِّكُمْ وَشِفَآءٌ لِّمَا فِى ٱلصُّدُورِ وَهُدًى وَرَحْمَةٌ لِّلْمُؤْمِنِينَ",
    english: "O humanity, there has come to you a warning from your Lord, a cure for what is in the hearts, a guide, and a mercy for the believers.",
    source: "Yūnus 10:57",
    category: "healing",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:16:69",
    type: "quran",
    arabic: "يَخْرُجُ مِنۢ بُطُونِهَا شَرَابٌ مُّخْتَلِفٌ أَلْوَٰنُهُۥ فِيهِ شِفَآءٌ لِّلنَّاسِ ۗ إِنَّ فِى ذَٰلِكَ لَـَٔايَةً لِّقَوْمٍ يَتَفَكَّرُونَ",
    english: "From their bellies comes forth liquid of varying colours, in which there is healing for people. Surely in this is a sign for those who reflect.",
    source: "Al-Naḥl 16:69",
    category: "healing",
    themes: ["reflection", "provision"],
    editorialStatus: "published",
  },
  {
    id: "q:17:82",
    type: "quran",
    arabic: "وَنُنَزِّلُ مِنَ ٱلْقُرْءَانِ مَا هُوَ شِفَآءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ",
    english: "We send down the Qur'an as a healing and mercy for the believers.",
    source: "Al-Isrāʼ 17:82",
    category: "healing",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:26:80",
    type: "quran",
    arabic: "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
    english: "And when I am ill, it is He who cures me.",
    source: "Al-Shuʿarāʼ 26:80",
    category: "healing",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:41:44",
    type: "quran",
    arabic: "قُلْ هُوَ لِلَّذِينَ ءَامَنُوا۟ هُدًى وَشِفَآءٌ",
    english: "Say: it is, for those who believe, a guidance and a cure.",
    source: "Fuṣṣilat 41:44",
    category: "healing",
    editorialStatus: "published",
  },

  // ═══ Qur'anic — Healing, protection, and wellbeing ═══

  {
    id: "q:21:83-84",
    type: "quran",
    arabic: "وَأَيُّوبَ إِذْ نَادَىٰ رَبَّهُۥٓ أَنِّى مَسَّنِىَ ٱلضُّرُّ وَأَنتَ أَرْحَمُ ٱلرَّٰحِمِينَ ۝ فَٱسْتَجَبْنَا لَهُۥ فَكَشَفْنَا مَا بِهِۦ مِن ضُرٍّ",
    english: "And Ayyūb, when he called out to his Lord: 'Affliction has touched me, and You are the Most Merciful of the merciful.' So We answered him and removed his affliction.",
    source: "Al-Anbiyāʼ 21:83–84",
    category: "healing",
    themes: ["supplication", "mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:38:41-42",
    type: "quran",
    arabic: "وَٱذْكُرْ عَبْدَنَآ أَيُّوبَ إِذْ نَادَىٰ رَبَّهُۥٓ أَنِّى مَسَّنِىَ ٱلشَّيْطَـٰنُ بِنُصْبٍ وَعَذَابٍ ۝ ٱرْكُضْ بِرِجْلِكَ ۖ هَـٰذَا مُغْتَسَلٌۢ بَارِدٌ وَشَرَابٌ",
    english: "And remember Our servant Ayyūb, when he called upon his Lord: 'Satan has afflicted me with distress and suffering.' We said: 'Strike the ground with your foot — here is cool water to wash and drink.'",
    source: "Ṣād 38:41–42",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:2:255",
    type: "quran",
    arabic: "ٱللَّهُ لَآ إِلَـٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَـٰوَٰتِ وَمَا فِى ٱلْأَرْضِ",
    english: "Allah — there is no god but He, the Ever-Living, the Sustainer of all existence. Neither drowsiness nor sleep overtakes Him. To Him belongs all that is in the heavens and the earth.",
    source: "Al-Baqarah 2:255",
    category: "healing",
    themes: ["trust"],
    editorialStatus: "published",
    scholarNotes: "Āyat al-Kursī — recited for protection and healing.",
  },
  {
    id: "q:10:107",
    type: "quran",
    arabic: "وَإِن يَمْسَسْكَ ٱللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُۥٓ إِلَّا هُوَ ۖ وَإِن يُرِدْكَ بِخَيْرٍ فَلَا رَآدَّ لِفَضْلِهِۦ",
    english: "If Allah touches you with harm, none can remove it but He. And if He intends good for you, none can repel His bounty.",
    source: "Yūnus 10:107",
    category: "healing",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:3:173",
    type: "quran",
    arabic: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ",
    english: "Allah is sufficient for us, and He is the best Disposer of affairs.",
    source: "Āl ʿImrān 3:173",
    category: "healing",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:6:17",
    type: "quran",
    arabic: "وَإِن يَمْسَسْكَ ٱللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُۥٓ إِلَّا هُوَ ۖ وَإِن يَمْسَسْكَ بِخَيْرٍ فَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ",
    english: "If Allah touches you with adversity, none can remove it except Him. And if He touches you with good, He is over all things competent.",
    source: "Al-Anʿām 6:17",
    category: "healing",
    themes: ["trust"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Prophetic medicine: general principles ═══

  {
    id: "h:bukhari:5678",
    type: "hadith",
    arabic: "مَا أَنْزَلَ اللَّهُ دَاءً إِلَّا أَنْزَلَ لَهُ شِفَاءً",
    english: "Allah has not sent down a disease without sending down a cure for it.",
    source: "Ṣaḥīḥ al-Bukhārī 5678",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2204",
    type: "hadith",
    arabic: "لِكُلِّ دَاءٍ دَوَاءٌ فَإِذَا أُصِيبَ دَوَاءُ الدَّاءِ بَرَأَ بِإِذْنِ اللَّهِ عَزَّ وَجَلَّ",
    english: "There is a remedy for every disease. When the remedy is applied to the disease, it is cured by the permission of Allah, the Exalted.",
    source: "Ṣaḥīḥ Muslim 2204",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:ibn-majah:3436",
    type: "hadith",
    arabic: "تَدَاوَوْا فَإِنَّ اللَّهَ عَزَّ وَجَلَّ لَمْ يَضَعْ دَاءً إِلَّا وَضَعَ لَهُ دَوَاءً غَيْرَ دَاءٍ وَاحِدٍ الْهَرَمُ",
    english: "Seek treatment, for Allah the Exalted has not created a disease without creating a cure for it — except for one disease: old age.",
    source: "Sunan Abī Dāwūd 3855",
    category: "healing",
    editorialStatus: "published",
  },

  // ═══ Hadith — Specific remedies ═══

  {
    id: "h:bukhari:5688",
    type: "hadith",
    arabic: "فِي الْحَبَّةِ السَّوْدَاءِ شِفَاءٌ مِنْ كُلِّ دَاءٍ إِلَّا السَّامَ",
    english: "There is healing in black seed for all ailments except death.",
    source: "Ṣaḥīḥ al-Bukhārī 5688",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5687",
    type: "hadith",
    arabic: "عَلَيْكُمْ بِهَذِهِ الْحَبَّةِ السَّوْدَاءِ فَإِنَّ فِيهَا شِفَاءً مِنْ كُلِّ دَاءٍ إِلَّا السَّامَ",
    english: "Use this black seed, for it contains a cure for every ailment except death.",
    source: "Ṣaḥīḥ al-Bukhārī 5687",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5684",
    type: "hadith",
    arabic: "اسْقِهِ عَسَلاً",
    english: "Let him drink honey.",
    source: "Ṣaḥīḥ al-Bukhārī 5684",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
    scholarNotes: "The Prophet ﷺ prescribed honey repeatedly for an abdominal ailment, saying 'Allah has spoken the truth, but your brother's abdomen has lied.'",
  },
  {
    id: "h:bukhari:5689",
    type: "hadith",
    arabic: "الشِّفَاءُ فِي ثَلاَثَةٍ شَرْبَةِ عَسَلٍ وَشَرْطَةِ مِحْجَمٍ وَكَيَّةِ نَارٍ وَأَنْهَى أُمَّتِي عَنِ الْكَىِّ",
    english: "Healing is in three things: a drink of honey, a cut of a cupping instrument, and cauterisation by fire. But I forbid my nation from cauterisation.",
    source: "Ṣaḥīḥ al-Bukhārī 5681",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5692",
    type: "hadith",
    arabic: "عَلَيْكُمْ بِهَذَا الْعُودِ الْهِنْدِيِّ فَإِنَّ فِيهِ سَبْعَةَ أَشْفِيَةٍ",
    english: "Use this Indian costus, for it contains seven cures.",
    source: "Ṣaḥīḥ al-Bukhārī 5692",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5696",
    type: "hadith",
    arabic: "عَلَيْكُمْ بِالتَّلْبِينَةِ فَإِنَّهَا مُجِمَّةٌ لِفُؤَادِ الْمَرِيضِ",
    english: "Use the talbīnah, for it soothes the heart of the sick person.",
    source: "Ṣaḥīḥ al-Bukhārī 5689",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5680",
    type: "hadith",
    arabic: "الْحُمَّى مِنْ فَيْحِ جَهَنَّمَ فَأَبْرِدُوهَا بِالْمَاءِ",
    english: "Fever is from the heat of Hellfire, so cool it with water.",
    source: "Ṣaḥīḥ al-Bukhārī 5723",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:3073",
    type: "hadith",
    arabic: "مَنْ تَصَبَّحَ بِسَبْعِ تَمَرَاتٍ عَجْوَةً لَمْ يَضُرَّهُ ذَلِكَ الْيَوْمَ سُمٌّ وَلاَ سِحْرٌ",
    english: "Whoever eats seven ʿajwah dates in the morning will not be harmed that day by poison or magic.",
    source: "Ṣaḥīḥ al-Bukhārī 5445",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2047",
    type: "hadith",
    arabic: "كُلُوا الزَّيْتَ وَادَّهِنُوا بِهِ فَإِنَّهُ مِنْ شَجَرَةٍ مُبَارَكَةٍ",
    english: "Eat olive oil and anoint yourselves with it, for it comes from a blessed tree.",
    source: "Sunan al-Tirmidhī 1851",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5356",
    type: "hadith",
    arabic: "الْكَمْأَةُ مِنَ الْمَنِّ وَمَاؤُهَا شِفَاءٌ لِلْعَيْنِ",
    english: "Truffles are a form of manna, and their water is a cure for the eyes.",
    source: "Ṣaḥīḥ al-Bukhārī 5708",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Cupping (ḥijāmah) ═══

  {
    id: "h:bukhari:5681",
    type: "hadith",
    arabic: "إِنَّ أَمْثَلَ مَا تَدَاوَيْتُمْ بِهِ الْحِجَامَةُ",
    english: "Indeed the best of what you treat yourselves with is cupping.",
    source: "Ṣaḥīḥ al-Bukhārī 5696",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:1577",
    type: "hadith",
    arabic: "احْتَجَمَ رَسُولُ اللَّهِ صلى الله عليه وسلم",
    english: "The Messenger of Allah ﷺ had himself cupped.",
    source: "Ṣaḥīḥ al-Bukhārī 5697",
    category: "healing",
    editorialStatus: "published",
  },

  // ═══ Hadith — Spiritual healing and ruqyah ═══

  {
    id: "h:muslim:2185",
    type: "hadith",
    arabic: "لاَ بَأْسَ بِالرُّقَى مَا لَمْ يَكُنْ فِيهِ شِرْكٌ",
    english: "There is nothing wrong with ruqyah as long as it does not involve shirk.",
    source: "Ṣaḥīḥ Muslim 2200",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5748",
    type: "hadith",
    arabic: "كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم إِذَا أَوَى إِلَى فِرَاشِهِ نَفَثَ فِي كَفَّيْهِ بِقُلْ هُوَ اللَّهُ أَحَدٌ وَبِالْمُعَوِّذَتَيْنِ جَمِيعًا ثُمَّ يَمْسَحُ بِهِمَا مَا اسْتَطَاعَ مِنْ جَسَدِهِ",
    english: "When the Messenger of Allah ﷺ would retire to bed, he would blow into his hands reciting al-Ikhlāṣ and the two protective sūrahs, then wipe over as much of his body as he could.",
    source: "Ṣaḥīḥ al-Bukhārī 5748",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5743",
    type: "hadith",
    arabic: "مَنْ قَرَأَ آيَةَ الْكُرْسِيِّ حِينَ يَأْوِي إِلَى فِرَاشِهِ لَمْ يَزَلْ عَلَيْهِ مِنَ اللَّهِ حَافِظٌ",
    english: "Whoever recites Āyat al-Kursī when he goes to bed, a guardian from Allah will remain with him.",
    source: "Ṣaḥīḥ al-Bukhārī 5010",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Illness, expiation, and visiting the sick ═══

  {
    id: "h:muslim:2573",
    type: "hadith",
    arabic: "مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ",
    english: "No fatigue, illness, anxiety, sorrow, harm, or grief afflicts a Muslim — not even the prick of a thorn — except that Allah expiates some of his sins through it.",
    source: "Ṣaḥīḥ al-Bukhārī 5641",
    category: "healing",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5640",
    type: "hadith",
    arabic: "مَا مِنْ مُسْلِمٍ يُصِيبُهُ أَذًى مِنْ مَرَضٍ فَمَا سِوَاهُ إِلاَّ حَطَّ اللَّهُ بِهِ سَيِّئَاتِهِ كَمَا تَحُطُّ الشَّجَرَةُ وَرَقَهَا",
    english: "No Muslim is afflicted with illness or hardship except that Allah removes his sins as a tree sheds its leaves.",
    source: "Ṣaḥīḥ al-Bukhārī 5660",
    category: "healing",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2572",
    type: "hadith",
    arabic: "إِنَّ الْمُؤْمِنَ إِذَا أَصَابَهُ السَّقَمُ ثُمَّ أَعْفَاهُ اللَّهُ مِنْهُ كَانَ كَفَّارَةً لِمَا مَضَى مِنْ ذُنُوبِهِ وَمَوْعِظَةً لَهُ فِيمَا يَسْتَقْبِلُ",
    english: "When a believer is afflicted by illness and Allah restores him, it is an expiation for his past sins and a lesson for the future.",
    source: "Musnad Aḥmad · Graded Ḥasan",
    category: "healing",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2568",
    type: "hadith",
    arabic: "إِنَّ عِظَمَ الْجَزَاءِ مَعَ عِظَمِ الْبَلاَءِ",
    english: "The greatest reward comes with the greatest trial.",
    source: "Sunan al-Tirmidhī 2396 · Graded Ḥasan",
    category: "healing",
    themes: ["patience"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Supplications for the sick ═══

  {
    id: "h:bukhari:5675",
    type: "hadith",
    arabic: "لاَ بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
    english: "No worry, it is a purification, if Allah wills.",
    source: "Ṣaḥīḥ al-Bukhārī 5656",
    category: "healing",
    editorialStatus: "published",
    scholarNotes: "Words said to comfort one who is ill.",
  },
  {
    id: "h:muslim:2191",
    type: "hadith",
    arabic: "أَذْهِبِ الْبَاسَ رَبَّ النَّاسِ اشْفِ وَأَنْتَ الشَّافِي لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ شِفَاءً لاَ يُغَادِرُ سَقَمًا",
    english: "Remove the hardship, O Lord of people. Grant cure, for You are the Healer. There is no cure except Your cure — a cure that leaves no illness behind.",
    source: "Ṣaḥīḥ al-Bukhārī 5742",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "h:abu-dawud:3106",
    type: "hadith",
    arabic: "مَنْ عَادَ مَرِيضًا لَمْ يَحْضُرْ أَجَلُهُ فَقَالَ عِنْدَهُ سَبْعَ مَرَّاتٍ أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ إِلاَّ عَافَاهُ اللَّهُ",
    english: "Whoever visits a sick person whose time has not come and says seven times: 'I ask Allah, the Mighty, Lord of the Mighty Throne, to cure you' — Allah will heal him.",
    source: "Sunan Abī Dāwūd 3106 · Graded Ṣaḥīḥ",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2191b",
    type: "hadith",
    arabic: "بِسْمِ اللَّهِ أَرْقِيكَ مِنْ كُلِّ شَىْءٍ يُؤْذِيكَ مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ اللَّهُ يَشْفِيكَ بِسْمِ اللَّهِ أَرْقِيكَ",
    english: "In the name of Allah I perform ruqyah for you, from everything that harms you, from the evil of every soul or envious eye — may Allah heal you. In the name of Allah I perform ruqyah for you.",
    source: "Ṣaḥīḥ Muslim 2186",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2065",
    type: "hadith",
    arabic: "مَا مَلأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ بِحَسْبِ ابْنِ آدَمَ أُكُلاَتٌ يُقِمْنَ صُلْبَهُ",
    english: "The son of Ādam fills no vessel worse than his stomach. Sufficient for the son of Ādam are a few morsels to keep his back straight.",
    source: "Sunan al-Tirmidhī 2380 · Graded Ṣaḥīḥ",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2191c",
    type: "hadith",
    arabic: "مَاءُ زَمْزَمَ لِمَا شُرِبَ لَهُ",
    english: "The water of Zamzam is for whatever purpose it is drunk.",
    source: "Sunan Ibn Mājah 3062 · Graded Ḥasan",
    category: "healing",
    themes: ["provision"],
    editorialStatus: "published",
  },

  // ═══ Qur'anic — Protective sūrahs ═══

  {
    id: "q:112:1-4",
    type: "quran",
    arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
    english: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. And there is none comparable to Him.",
    source: "Al-Ikhlāṣ 112:1–4",
    category: "healing",
    themes: ["supplication"],
    editorialStatus: "published",
    scholarNotes: "One of the protective sūrahs recited for healing.",
  },
  {
    id: "q:113:1-5",
    type: "quran",
    arabic: "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّـٰثَـٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    english: "Say: I seek refuge in the Lord of the daybreak, from the evil of what He has created, from the evil of the night when it settles, from the evil of those who blow on knots, and from the evil of the envier when he envies.",
    source: "Al-Falaq 113:1–5",
    category: "healing",
    editorialStatus: "published",
  },
  {
    id: "q:114:1-6",
    type: "quran",
    arabic: "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَـٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
    english: "Say: I seek refuge in the Lord of humankind, the King of humankind, the God of humankind, from the evil of the retreating whisperer, who whispers into the hearts of humankind, from among jinn and humankind.",
    source: "Al-Nās 114:1–6",
    category: "healing",
    editorialStatus: "published",
  },

  // ═══ Hadith — The sick and afterlife ═══

  {
    id: "h:bukhari:5641",
    type: "hadith",
    arabic: "عُودُوا الْمَرِيضَ وَأَطْعِمُوا الْجَائِعَ وَفُكُّوا الْعَانِيَ",
    english: "Visit the sick, feed the hungry, and set free the captive.",
    source: "Ṣaḥīḥ al-Bukhārī 5649",
    category: "healing",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2568a",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ عَزَّ وَجَلَّ يَقُولُ يَوْمَ الْقِيَامَةِ يَا ابْنَ آدَمَ مَرِضْتُ فَلَمْ تَعُدْنِي",
    english: "Allah the Exalted will say on the Day of Resurrection: 'O son of Ādam, I was ill and you did not visit Me.'",
    source: "Ṣaḥīḥ Muslim 2569",
    category: "healing",
    themes: ["mercy"],
    editorialStatus: "published",
    scholarNotes: "A ḥadīth qudsī; the servant asks how he can visit the Lord, and is told: 'Did you not know that My servant was ill and you did not visit him? Had you visited him you would have found Me with him.'",
  },
];
