import type { RevelationEntry } from "../../schema";

/**
 * Theme: Knowledge (العلم)
 *
 * The pursuit of knowledge, the obligation of learning,
 * wisdom, understanding, and the honour of scholarship.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const knowledgeCollection: RevelationEntry[] = [
  {
    id: "q:96:1-5",
    type: "quran",
    arabic: "ٱقْرَأْ بِٱسْمِ رَبِّكَ ٱلَّذِى خَلَقَ ۝ خَلَقَ ٱلْإِنسَـٰنَ مِنْ عَلَقٍ ۝ ٱقْرَأْ وَرَبُّكَ ٱلْأَكْرَمُ ۝ ٱلَّذِى عَلَّمَ بِٱلْقَلَمِ ۝ عَلَّمَ ٱلْإِنسَـٰنَ مَا لَمْ يَعْلَمْ",
    english: "Read in the name of your Lord who created — created man from a clinging substance. Read, and your Lord is the Most Generous — who taught by the pen, taught man that which he knew not.",
    source: "Al-ʿAlaq 96:1–5",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:39:9",
    type: "quran",
    arabic: "قُلْ هَلْ يَسْتَوِى ٱلَّذِينَ يَعْلَمُونَ وَٱلَّذِينَ لَا يَعْلَمُونَ ۗ إِنَّمَا يَتَذَكَّرُ أُو۟لُوا۟ ٱلْأَلْبَـٰبِ",
    english: "Say: are those who know equal to those who do not know? Only people of understanding will take heed.",
    source: "Al-Zumar 39:9",
    category: "knowledge",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:20:114",
    type: "quran",
    arabic: "وَقُل رَّبِّ زِدْنِى عِلْمًا",
    english: "And say: my Lord, increase me in knowledge.",
    source: "Ṭā Hā 20:114",
    category: "knowledge",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:58:11",
    type: "quran",
    arabic: "يَرْفَعِ ٱللَّهُ ٱلَّذِينَ ءَامَنُوا۟ مِنكُمْ وَٱلَّذِينَ أُوتُوا۟ ٱلْعِلْمَ دَرَجَـٰتٍ",
    english: "Allah will elevate those of you who believe and those who are given knowledge, by degrees.",
    source: "Al-Mujādilah 58:11",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:35:28",
    type: "quran",
    arabic: "إِنَّمَا يَخْشَى ٱللَّهَ مِنْ عِبَادِهِ ٱلْعُلَمَـٰٓؤُا۟",
    english: "Only those of His servants who have knowledge truly fear Allah.",
    source: "Fāṭir 35:28",
    category: "knowledge",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:2:269",
    type: "quran",
    arabic: "يُؤْتِى ٱلْحِكْمَةَ مَن يَشَآءُ ۚ وَمَن يُؤْتَ ٱلْحِكْمَةَ فَقَدْ أُوتِىَ خَيْرًا كَثِيرًا",
    english: "He grants wisdom to whom He wills, and whoever is granted wisdom has indeed been given much good.",
    source: "Al-Baqarah 2:269",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:17:85",
    type: "quran",
    arabic: "وَمَآ أُوتِيتُم مِّنَ ٱلْعِلْمِ إِلَّا قَلِيلًا",
    english: "And you have been given of knowledge only a little.",
    source: "Al-Isrāʼ 17:85",
    category: "knowledge",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:3:18",
    type: "quran",
    arabic: "شَهِدَ ٱللَّهُ أَنَّهُۥ لَآ إِلَـٰهَ إِلَّا هُوَ وَٱلْمَلَـٰٓئِكَةُ وَأُو۟لُوا۟ ٱلْعِلْمِ قَآئِمًۢا بِٱلْقِسْطِ",
    english: "Allah bears witness that there is no god but He — and so do the angels and people of knowledge — maintaining justice.",
    source: "Āl ʿImrān 3:18",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:2:31-32",
    type: "quran",
    arabic: "وَعَلَّمَ ءَادَمَ ٱلْأَسْمَآءَ كُلَّهَا ثُمَّ عَرَضَهُمْ عَلَى ٱلْمَلَـٰٓئِكَةِ فَقَالَ أَنۢبِـُٔونِى بِأَسْمَآءِ هَـٰٓؤُلَآءِ إِن كُنتُمْ صَـٰدِقِينَ ۝ قَالُوا۟ سُبْحَـٰنَكَ لَا عِلْمَ لَنَآ إِلَّا مَا عَلَّمْتَنَآ",
    english: "And He taught Ādam the names of all things, then presented them to the angels and said: 'Tell Me the names of these, if you are truthful.' They said: 'Glory be to You! We have no knowledge except what You have taught us.'",
    source: "Al-Baqarah 2:31–32",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:16:43",
    type: "quran",
    arabic: "فَسْـَٔلُوٓا۟ أَهْلَ ٱلذِّكْرِ إِن كُنتُمْ لَا تَعْلَمُونَ",
    english: "Ask the people of knowledge if you do not know.",
    source: "Al-Naḥl 16:43",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:12:76",
    type: "quran",
    arabic: "وَفَوْقَ كُلِّ ذِى عِلْمٍ عَلِيمٌ",
    english: "And above every person of knowledge there is one more knowing.",
    source: "Yūsuf 12:76",
    category: "knowledge",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:29:43",
    type: "quran",
    arabic: "وَتِلْكَ ٱلْأَمْثَـٰلُ نَضْرِبُهَا لِلنَّاسِ ۖ وَمَا يَعْقِلُهَآ إِلَّا ٱلْعَـٰلِمُونَ",
    english: "These are the parables We set forth for people, but none will understand them except the knowledgeable.",
    source: "Al-ʿAnkabūt 29:43",
    category: "knowledge",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:4:162",
    type: "quran",
    arabic: "لَّـٰكِنِ ٱلرَّٰسِخُونَ فِى ٱلْعِلْمِ مِنْهُمْ وَٱلْمُؤْمِنُونَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ",
    english: "But those firmly grounded in knowledge among them and the believers — they believe in what has been revealed to you and what was revealed before you.",
    source: "Al-Nisāʼ 4:162",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "q:3:7",
    type: "quran",
    arabic: "وَٱلرَّٰسِخُونَ فِى ٱلْعِلْمِ يَقُولُونَ ءَامَنَّا بِهِۦ كُلٌّ مِّنْ عِندِ رَبِّنَا",
    english: "And those firmly grounded in knowledge say: 'We believe in it — all of it is from our Lord.'",
    source: "Āl ʿImrān 3:7",
    category: "knowledge",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:55:1-4",
    type: "quran",
    arabic: "ٱلرَّحْمَـٰنُ ۝ عَلَّمَ ٱلْقُرْءَانَ ۝ خَلَقَ ٱلْإِنسَـٰنَ ۝ عَلَّمَهُ ٱلْبَيَانَ",
    english: "The Most Merciful. He taught the Qur'an. He created man. He taught him speech.",
    source: "Al-Raḥmān 55:1–4",
    category: "knowledge",
    themes: ["mercy"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Knowledge ═══

  {
    id: "h:muslim:2699",
    type: "hadith",
    arabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ",
    english: "Whoever takes a path in pursuit of knowledge, Allah will ease for him a path to Paradise.",
    source: "Ṣaḥīḥ Muslim 2699",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:ibn-majah:224",
    type: "hadith",
    arabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ",
    english: "Seeking knowledge is an obligation upon every Muslim.",
    source: "Sunan Ibn Mājah 224 · Graded Ṣaḥīḥ by al-Albānī",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:71",
    type: "hadith",
    arabic: "مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ",
    english: "When Allah wills good for someone, He grants him understanding of the religion.",
    source: "Ṣaḥīḥ al-Bukhārī 71",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:100",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ لاَ يَقْبِضُ الْعِلْمَ انْتِزَاعًا يَنْتَزِعُهُ مِنَ الْعِبَادِ وَلَكِنْ يَقْبِضُ الْعِلْمَ بِقَبْضِ الْعُلَمَاءِ",
    english: "Allah does not take away knowledge by snatching it from people, but He takes it away by taking away the scholars.",
    source: "Ṣaḥīḥ al-Bukhārī 100",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:abu-dawud:3641",
    type: "hadith",
    arabic: "إِنَّ الْعُلَمَاءَ وَرَثَةُ الأَنْبِيَاءِ إِنَّ الأَنْبِيَاءَ لَمْ يُوَرِّثُوا دِينَارًا وَلاَ دِرْهَمًا إِنَّمَا وَرَّثُوا الْعِلْمَ",
    english: "The scholars are the heirs of the Prophets. The Prophets did not leave behind gold or silver coins — they only left behind knowledge.",
    source: "Sunan Abī Dāwūd 3641 · Graded Ṣaḥīḥ",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2699b",
    type: "hadith",
    arabic: "وَمَا اجْتَمَعَ قَوْمٌ فِي بَيْتٍ مِنْ بُيُوتِ اللَّهِ يَتْلُونَ كِتَابَ اللَّهِ وَيَتَدَارَسُونَهُ بَيْنَهُمْ إِلاَّ نَزَلَتْ عَلَيْهِمُ السَّكِينَةُ وَغَشِيَتْهُمُ الرَّحْمَةُ",
    english: "No people gather in one of the houses of Allah to recite the Book of Allah and study it together, except that tranquillity descends upon them and mercy covers them.",
    source: "Ṣaḥīḥ Muslim 2699",
    category: "knowledge",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:3461",
    type: "hadith",
    arabic: "بَلِّغُوا عَنِّي وَلَوْ آيَةً",
    english: "Convey from me, even if it is a single verse.",
    source: "Ṣaḥīḥ al-Bukhārī 3461",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:1631",
    type: "hadith",
    arabic: "إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلاَّ مِنْ ثَلاَثَةٍ إِلاَّ مِنْ صَدَقَةٍ جَارِيَةٍ أَوْ عِلْمٍ يُنْتَفَعُ بِهِ أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
    english: "When a person dies, their deeds come to an end except for three: an ongoing charity, knowledge from which benefit is derived, or a righteous child who prays for them.",
    source: "Ṣaḥīḥ Muslim 1631",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2685",
    type: "hadith",
    arabic: "نَضَّرَ اللَّهُ امْرَأً سَمِعَ مِنَّا شَيْئًا فَبَلَّغَهُ كَمَا سَمِعَهُ فَرُبَّ مُبَلَّغٍ أَوْعَى مِنْ سَامِعٍ",
    english: "May Allah brighten the face of a person who hears something from us and conveys it as he heard it, for perhaps the one it is conveyed to understands it better than the one who heard it.",
    source: "Sunan al-Tirmidhī 2657 · Graded Ṣaḥīḥ",
    category: "knowledge",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:67",
    type: "hadith",
    arabic: "يَسِّرُوا وَلاَ تُعَسِّرُوا وَبَشِّرُوا وَلاَ تُنَفِّرُوا",
    english: "Make things easy and do not make them difficult. Give good tidings and do not repel people.",
    source: "Ṣaḥīḥ al-Bukhārī 69",
    category: "knowledge",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2682",
    type: "hadith",
    arabic: "فَضْلُ الْعَالِمِ عَلَى الْعَابِدِ كَفَضْلِ الْقَمَرِ لَيْلَةَ الْبَدْرِ عَلَى سَائِرِ الْكَوَاكِبِ",
    english: "The superiority of the scholar over the worshipper is like the superiority of the full moon over the rest of the stars.",
    source: "Sunan Abī Dāwūd 3641 · Graded Ṣaḥīḥ",
    category: "knowledge",
    editorialStatus: "published",
  },
];
