import type { RevelationEntry } from "../../schema";

/**
 * Theme: Mercy (الرحمة)
 *
 * Divine mercy, compassion between people,
 * and the Prophetic model of gentleness.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const mercyCollection: RevelationEntry[] = [
  {
    id: "q:21:107",
    type: "quran",
    arabic: "وَمَآ أَرْسَلْنَـٰكَ إِلَّا رَحْمَةً لِّلْعَـٰلَمِينَ",
    english: "We have not sent you except as a mercy for all the worlds.",
    source: "Al-Anbiyāʼ 21:107",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:6:54",
    type: "quran",
    arabic: "كَتَبَ رَبُّكُمْ عَلَىٰ نَفْسِهِ ٱلرَّحْمَةَ",
    english: "Your Lord has prescribed mercy upon Himself.",
    source: "Al-Anʿām 6:54",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:7:156",
    type: "quran",
    arabic: "وَرَحْمَتِى وَسِعَتْ كُلَّ شَىْءٍ",
    english: "My mercy encompasses all things.",
    source: "Al-Aʿrāf 7:156",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:39:53",
    type: "quran",
    arabic: "قُلْ يَـٰعِبَادِىَ ٱلَّذِينَ أَسْرَفُوا۟ عَلَىٰٓ أَنفُسِهِمْ لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ ۚ إِنَّ ٱللَّهَ يَغْفِرُ ٱلذُّنُوبَ جَمِيعًا ۚ إِنَّهُۥ هُوَ ٱلْغَفُورُ ٱلرَّحِيمُ",
    english: "Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins. He is truly the All-Forgiving, Most Merciful.",
    source: "Al-Zumar 39:53",
    category: "mercy",
    themes: ["purification"],
    editorialStatus: "published",
  },
  {
    id: "q:12:87",
    type: "quran",
    arabic: "وَلَا تَا۟يْـَٔسُوا۟ مِن رَّوْحِ ٱللَّهِ ۖ إِنَّهُۥ لَا يَا۟يْـَٔسُ مِن رَّوْحِ ٱللَّهِ إِلَّا ٱلْقَوْمُ ٱلْكَـٰفِرُونَ",
    english: "And do not despair of the relief of Allah. Indeed, no one despairs of the relief of Allah except the disbelieving people.",
    source: "Yūsuf 12:87",
    category: "mercy",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:2:286",
    type: "quran",
    arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
    english: "Allah does not burden a soul beyond what it can bear.",
    source: "Al-Baqarah 2:286",
    category: "mercy",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "q:23:118",
    type: "quran",
    arabic: "وَقُل رَّبِّ ٱغْفِرْ وَٱرْحَمْ وَأَنتَ خَيْرُ ٱلرَّٰحِمِينَ",
    english: "And say: my Lord, forgive and have mercy, for You are the best of the merciful.",
    source: "Al-Muʼminūn 23:118",
    category: "mercy",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:1:1-3",
    type: "quran",
    arabic: "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ ۝ ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ ۝ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ",
    english: "In the name of Allah, the Most Merciful, the Especially Merciful. All praise is due to Allah, Lord of all the worlds. The Most Merciful, the Especially Merciful.",
    source: "Al-Fātiḥah 1:1–3",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:6:12",
    type: "quran",
    arabic: "كَتَبَ عَلَىٰ نَفْسِهِ ٱلرَّحْمَةَ",
    english: "He has decreed mercy upon Himself.",
    source: "Al-Anʿām 6:12",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:57:9",
    type: "quran",
    arabic: "هُوَ ٱلَّذِى يُنَزِّلُ عَلَىٰ عَبْدِهِۦٓ ءَايَـٰتٍۭ بَيِّنَـٰتٍ لِّيُخْرِجَكُم مِّنَ ٱلظُّلُمَـٰتِ إِلَى ٱلنُّورِ ۚ وَإِنَّ ٱللَّهَ بِكُمْ لَرَءُوفٌ رَّحِيمٌ",
    english: "It is He who sends down clear revelations upon His servant, to lead you out of darkness into light. And indeed, Allah is to you Full of Kindness, Most Merciful.",
    source: "Al-Ḥadīd 57:9",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "q:19:96",
    type: "quran",
    arabic: "إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ سَيَجْعَلُ لَهُمُ ٱلرَّحْمَـٰنُ وُدًّا",
    english: "Indeed, those who believe and do righteous deeds — the Most Merciful will bestow upon them love.",
    source: "Maryam 19:96",
    category: "mercy",
    editorialStatus: "published",
  },

  // ═══ Hadith — Mercy ═══

  {
    id: "h:bukhari:6000",
    type: "hadith",
    arabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
    english: "The merciful are shown mercy by the Most Merciful. Be merciful to those on earth, and the One above the heavens will be merciful to you.",
    source: "Sunan Abī Dāwūd 4941 · Graded Ṣaḥīḥ",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2319",
    type: "hadith",
    arabic: "لاَ يَرْحَمُ اللَّهُ مَنْ لاَ يَرْحَمُ النَّاسَ",
    english: "Allah does not show mercy to those who do not show mercy to people.",
    source: "Ṣaḥīḥ al-Bukhārī 7376",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2752",
    type: "hadith",
    arabic: "جَعَلَ اللَّهُ الرَّحْمَةَ مِائَةَ جُزْءٍ فَأَمْسَكَ عِنْدَهُ تِسْعَةً وَتِسْعِينَ جُزْءًا وَأَنْزَلَ فِي الأَرْضِ جُزْءًا وَاحِدًا فَمِنْ ذَلِكَ الْجُزْءِ يَتَرَاحَمُ الْخَلْقُ",
    english: "Allah divided mercy into one hundred parts. He retained ninety-nine parts with Himself and sent down one part to earth. From that one part comes all the mercy creatures show one another.",
    source: "Ṣaḥīḥ al-Bukhārī 6000",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6005",
    type: "hadith",
    arabic: "مَنْ لاَ يَرْحَمْ لاَ يُرْحَمْ",
    english: "He who does not show mercy will not be shown mercy.",
    source: "Ṣaḥīḥ al-Bukhārī 5997",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2593",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ وَيُعْطِي عَلَى الرِّفْقِ مَا لاَ يُعْطِي عَلَى الْعُنْفِ وَمَا لاَ يُعْطِي عَلَى مَا سِوَاهُ",
    english: "Allah is gentle and loves gentleness, and He grants through gentleness what He does not grant through harshness, and what He does not grant through anything else.",
    source: "Ṣaḥīḥ Muslim 2593",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2594",
    type: "hadith",
    arabic: "إِنَّ الرِّفْقَ لاَ يَكُونُ فِي شَىْءٍ إِلاَّ زَانَهُ وَلاَ يُنْزَعُ مِنْ شَىْءٍ إِلاَّ شَانَهُ",
    english: "Gentleness does not enter anything except that it beautifies it, and it is not removed from anything except that it disfigures it.",
    source: "Ṣaḥīḥ Muslim 2594",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2588",
    type: "hadith",
    arabic: "مَنْ لاَ يَرْحَمِ النَّاسَ لاَ يَرْحَمْهُ اللَّهُ",
    english: "He who shows no mercy to people, Allah will show no mercy to him.",
    source: "Ṣaḥīḥ Muslim 2319",
    category: "mercy",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5999",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ لاَ يَنْزِعُ الرَّحْمَةَ إِلاَّ مِنْ شَقِيٍّ",
    english: "Allah does not remove mercy except from one who is wretched.",
    source: "Sunan Abī Dāwūd 4942 · Graded Ṣaḥīḥ",
    category: "mercy",
    editorialStatus: "published",
  },
];
