import type { RevelationEntry } from "../../schema";

/**
 * Theme: Patience (الصبر)
 *
 * Steadfastness in trial, perseverance through hardship,
 * and the Prophetic model of endurance.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const patienceCollection: RevelationEntry[] = [
  // ═══ Qur'anic — Patience commanded ═══

  {
    id: "q:2:153",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ ۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ",
    english: "O believers, seek comfort in patience and prayer. Allah is truly with those who are patient.",
    source: "Al-Baqarah 2:153",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:2:155-156",
    type: "quran",
    arabic: "وَلَنَبْلُوَنَّكُم بِشَىْءٍ مِّنَ ٱلْخَوْفِ وَٱلْجُوعِ وَنَقْصٍ مِّنَ ٱلْأَمْوَٰلِ وَٱلْأَنفُسِ وَٱلثَّمَرَٰتِ ۗ وَبَشِّرِ ٱلصَّـٰبِرِينَ ۝ ٱلَّذِينَ إِذَآ أَصَـٰبَتْهُم مُّصِيبَةٌ قَالُوٓا۟ إِنَّا لِلَّهِ وَإِنَّآ إِلَيْهِ رَٰجِعُونَ",
    english: "We will certainly test you with a touch of fear and famine, and loss of property, life, and crops. But give good news to those who patiently endure — who, when afflicted with a calamity, say: 'Indeed, to Allah we belong and to Him we shall return.'",
    source: "Al-Baqarah 2:155–156",
    category: "patience",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:3:200",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱصْبِرُوا۟ وَصَابِرُوا۟ وَرَابِطُوا۟ وَٱتَّقُوا۟ ٱللَّهَ لَعَلَّكُمْ تُفْلِحُونَ",
    english: "O believers, be patient, stand firm, remain prepared, and be mindful of Allah, so you may be successful.",
    source: "Āl ʿImrān 3:200",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:16:127",
    type: "quran",
    arabic: "وَٱصْبِرْ وَمَا صَبْرُكَ إِلَّا بِٱللَّهِ",
    english: "Be patient, for your patience is only with Allah's help.",
    source: "Al-Naḥl 16:127",
    category: "patience",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:39:10",
    type: "quran",
    arabic: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ",
    english: "The patient will be given their reward without measure.",
    source: "Al-Zumar 39:10",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:3:186",
    type: "quran",
    arabic: "وَإِن تَصْبِرُوا۟ وَتَتَّقُوا۟ فَإِنَّ ذَٰلِكَ مِنْ عَزْمِ ٱلْأُمُورِ",
    english: "If you are patient and mindful of Allah — surely this is a matter of great resolve.",
    source: "Āl ʿImrān 3:186",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:11:115",
    type: "quran",
    arabic: "وَٱصْبِرْ فَإِنَّ ٱللَّهَ لَا يُضِيعُ أَجْرَ ٱلْمُحْسِنِينَ",
    english: "And be patient, for Allah does not let the reward of the good-doers go to waste.",
    source: "Hūd 11:115",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:94:5-6",
    type: "quran",
    arabic: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ ٱلْعُسْرِ يُسْرًا",
    english: "So truly with hardship comes ease. Truly with hardship comes ease.",
    source: "Al-Sharḥ 94:5–6",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:65:7",
    type: "quran",
    arabic: "سَيَجْعَلُ ٱللَّهُ بَعْدَ عُسْرٍ يُسْرًا",
    english: "Allah will bring about ease after hardship.",
    source: "Al-Ṭalāq 65:7",
    category: "patience",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:2:45",
    type: "quran",
    arabic: "وَٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى ٱلْخَـٰشِعِينَ",
    english: "And seek help through patience and prayer. It is indeed difficult except for the humble.",
    source: "Al-Baqarah 2:45",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:103:1-3",
    type: "quran",
    arabic: "وَٱلْعَصْرِ ۝ إِنَّ ٱلْإِنسَـٰنَ لَفِى خُسْرٍ ۝ إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ وَتَوَاصَوْا۟ بِٱلْحَقِّ وَتَوَاصَوْا۟ بِٱلصَّبْرِ",
    english: "By time, indeed mankind is in loss — except those who believe, do good, urge one another to the truth, and urge one another to patience.",
    source: "Al-ʿAṣr 103:1–3",
    category: "patience",
    themes: ["knowledge"],
    editorialStatus: "published",
  },
  {
    id: "q:31:17",
    type: "quran",
    arabic: "وَٱصْبِرْ عَلَىٰ مَآ أَصَابَكَ ۖ إِنَّ ذَٰلِكَ مِنْ عَزْمِ ٱلْأُمُورِ",
    english: "And bear with patience whatever befalls you. Surely this is a matter of great resolve.",
    source: "Luqmān 31:17",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:46:35",
    type: "quran",
    arabic: "فَٱصْبِرْ كَمَا صَبَرَ أُو۟لُوا۟ ٱلْعَزْمِ مِنَ ٱلرُّسُلِ",
    english: "So be patient, as the messengers of firm resolve were patient.",
    source: "Al-Aḥqāf 46:35",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:28:80",
    type: "quran",
    arabic: "وَلَا يُلَقَّىٰهَآ إِلَّا ٱلصَّـٰبِرُونَ",
    english: "But none will attain this except the steadfast.",
    source: "Al-Qaṣaṣ 28:80",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:8:46",
    type: "quran",
    arabic: "وَٱصْبِرُوٓا۟ ۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ",
    english: "And be patient. Indeed, Allah is with the patient.",
    source: "Al-Anfāl 8:46",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:3:146",
    type: "quran",
    arabic: "وَٱللَّهُ يُحِبُّ ٱلصَّـٰبِرِينَ",
    english: "And Allah loves the patient.",
    source: "Āl ʿImrān 3:146",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:12:90",
    type: "quran",
    arabic: "إِنَّهُۥ مَن يَتَّقِ وَيَصْبِرْ فَإِنَّ ٱللَّهَ لَا يُضِيعُ أَجْرَ ٱلْمُحْسِنِينَ",
    english: "Whoever is mindful of Allah and patient — then indeed, Allah does not allow the reward of the good-doers to be lost.",
    source: "Yūsuf 12:90",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "q:42:43",
    type: "quran",
    arabic: "وَلَمَن صَبَرَ وَغَفَرَ إِنَّ ذَٰلِكَ لَمِنْ عَزْمِ ٱلْأُمُورِ",
    english: "And whoever is patient and forgives — indeed, that is of the matters of great resolve.",
    source: "Al-Shūrā 42:43",
    category: "patience",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:90:4",
    type: "quran",
    arabic: "لَقَدْ خَلَقْنَا ٱلْإِنسَـٰنَ فِى كَبَدٍ",
    english: "We have certainly created man in hardship.",
    source: "Al-Balad 90:4",
    category: "patience",
    themes: ["reflection"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Patience ═══

  {
    id: "h:bukhari:1469",
    type: "hadith",
    arabic: "وَمَنْ يَتَصَبَّرْ يُصَبِّرْهُ اللَّهُ وَمَا أُعْطِيَ أَحَدٌ عَطَاءً خَيْرًا وَأَوْسَعَ مِنَ الصَّبْرِ",
    english: "Whoever remains patient, Allah will make him patient. No one is given a gift better and more encompassing than patience.",
    source: "Ṣaḥīḥ al-Bukhārī 1469",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2999",
    type: "hadith",
    arabic: "عَجَبًا لِأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ وَلَيْسَ ذَاكَ لِأَحَدٍ إِلَّا لِلْمُؤْمِنِ إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ",
    english: "How wonderful is the affair of the believer, for all of it is good — and that is for no one except the believer. If something good happens, he is grateful, and that is good for him. If something harmful befalls him, he is patient, and that is good for him.",
    source: "Ṣaḥīḥ Muslim 2999",
    category: "patience",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2396",
    type: "hadith",
    arabic: "إِنَّ عِظَمَ الْجَزَاءِ مَعَ عِظَمِ الْبَلَاءِ وَإِنَّ اللَّهَ إِذَا أَحَبَّ قَوْمًا ابْتَلَاهُمْ فَمَنْ رَضِيَ فَلَهُ الرِّضَا وَمَنْ سَخِطَ فَلَهُ السَّخَطُ",
    english: "The greatest reward comes with the greatest trial. When Allah loves a people, He tests them. Whoever is content will have contentment, and whoever is resentful will have resentment.",
    source: "Sunan al-Tirmidhī 2396 · Graded Ḥasan",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5653",
    type: "hadith",
    arabic: "إِنَّمَا الصَّبْرُ عِنْدَ الصَّدْمَةِ الأُولَى",
    english: "True patience is at the first stroke of calamity.",
    source: "Ṣaḥīḥ al-Bukhārī 1283",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:7405",
    type: "hadith",
    arabic: "إِذَا ابْتَلَيْتُ عَبْدِي بِحَبِيبَتَيْهِ فَصَبَرَ عَوَّضْتُهُ مِنْهُمَا الْجَنَّةَ",
    english: "When I test My servant by taking away his two beloved ones (his eyes) and he shows patience, I will compensate him with Paradise.",
    source: "Ṣaḥīḥ al-Bukhārī 5653",
    category: "patience",
    editorialStatus: "published",
    scholarNotes: "A ḥadīth qudsī — words of Allah related by the Prophet ﷺ.",
  },
  {
    id: "h:bukhari:5645",
    type: "hadith",
    arabic: "مَا يَزَالُ الْبَلاَءُ بِالْمُؤْمِنِ وَالْمُؤْمِنَةِ فِي نَفْسِهِ وَوَلَدِهِ وَمَالِهِ حَتَّى يَلْقَى اللَّهَ وَمَا عَلَيْهِ خَطِيئَةٌ",
    english: "Trials will not cease for the believing man and believing woman — in self, in children, in wealth — until they meet Allah with no sin upon them.",
    source: "Sunan al-Tirmidhī 2399 · Graded Ṣaḥīḥ",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6424",
    type: "hadith",
    arabic: "أَشَدُّ النَّاسِ بَلاَءً الأَنْبِيَاءُ ثُمَّ الأَمْثَلُ فَالأَمْثَلُ",
    english: "The most severely tested people are the Prophets, then the next best, then the next best.",
    source: "Sunan al-Tirmidhī 2398 · Graded Ṣaḥīḥ",
    category: "patience",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:918",
    type: "hadith",
    arabic: "إِنَّ لِلَّهِ مَا أَخَذَ وَلَهُ مَا أَعْطَى وَكُلٌّ عِنْدَهُ بِأَجَلٍ مُسَمًّى فَلْتَصْبِرْ وَلْتَحْتَسِبْ",
    english: "To Allah belongs what He has taken, and to Him belongs what He has given. Everything has an appointed time. So be patient and seek reward.",
    source: "Ṣaḥīḥ al-Bukhārī 1284",
    category: "patience",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2803",
    type: "hadith",
    arabic: "حُفَّتِ الْجَنَّةُ بِالْمَكَارِهِ وَحُفَّتِ النَّارُ بِالشَّهَوَاتِ",
    english: "Paradise is surrounded by hardships, and Hellfire is surrounded by desires.",
    source: "Ṣaḥīḥ Muslim 2822",
    category: "patience",
    editorialStatus: "published",
  },
];
