import type { RevelationEntry } from "../../schema";

/**
 * Theme: Provision (الرزق)
 *
 * Food, sustenance, the natural world as provision,
 * and Prophetic guidance on nourishment and consumption.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const provisionCollection: RevelationEntry[] = [
  // ═══ Qur'anic — Blessed foods ═══

  {
    id: "q:95:1",
    type: "quran",
    arabic: "وَٱلتِّينِ وَٱلزَّيْتُونِ",
    english: "By the fig and the olive.",
    source: "Al-Tīn 95:1",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "q:24:35",
    type: "quran",
    arabic: "يُوقَدُ مِن شَجَرَةٍ مُّبَـٰرَكَةٍ زَيْتُونَةٍ لَّا شَرْقِيَّةٍ وَلَا غَرْبِيَّةٍ يَكَادُ زَيْتُهَا يُضِىٓءُ وَلَوْ لَمْ تَمْسَسْهُ نَارٌ",
    english: "Lit from a blessed olive tree, neither eastern nor western, whose oil would almost glow even if untouched by fire.",
    source: "Al-Nūr 24:35",
    category: "provision",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:47:15",
    type: "quran",
    arabic: "فِيهَآ أَنْهَـٰرٌ مِّن مَّآءٍ غَيْرِ ءَاسِنٍ وَأَنْهَـٰرٌ مِّن لَّبَنٍ لَّمْ يَتَغَيَّرْ طَعْمُهُۥ وَأَنْهَـٰرٌ مِّنْ خَمْرٍ لَّذَّةٍ لِّلشَّـٰرِبِينَ وَأَنْهَـٰرٌ مِّنْ عَسَلٍ مُّصَفًّى",
    english: "In it are rivers of water, never stale; rivers of milk whose taste never changes; rivers of wine, a delight for those who drink; and rivers of pure honey.",
    source: "Muḥammad 47:15",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "q:6:99",
    type: "quran",
    arabic: "وَهُوَ ٱلَّذِىٓ أَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَأَخْرَجْنَا بِهِۦ نَبَاتَ كُلِّ شَىْءٍ",
    english: "It is He who sends down water from the sky, and with it We bring forth the growth of every kind.",
    source: "Al-Anʿām 6:99",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:6:141",
    type: "quran",
    arabic: "وَهُوَ ٱلَّذِىٓ أَنشَأَ جَنَّـٰتٍ مَّعْرُوشَـٰتٍ وَغَيْرَ مَعْرُوشَـٰتٍ وَٱلنَّخْلَ وَٱلزَّرْعَ مُخْتَلِفًا أُكُلُهُۥ وَٱلزَّيْتُونَ وَٱلرُّمَّانَ",
    english: "It is He who produces gardens, both trellised and untrellised, and date palms, and crops of different flavour, and olives and pomegranates.",
    source: "Al-Anʿām 6:141",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:36:33-35",
    type: "quran",
    arabic: "وَءَايَةٌ لَّهُمُ ٱلْأَرْضُ ٱلْمَيْتَةُ أَحْيَيْنَـٰهَا وَأَخْرَجْنَا مِنْهَا حَبًّا فَمِنْهُ يَأْكُلُونَ ۝ وَجَعَلْنَا فِيهَا جَنَّـٰتٍ مِّن نَّخِيلٍ وَأَعْنَـٰبٍ وَفَجَّرْنَا فِيهَا مِنَ ٱلْعُيُونِ ۝ لِيَأْكُلُوا۟ مِن ثَمَرِهِۦ وَمَا عَمِلَتْهُ أَيْدِيهِمْ ۖ أَفَلَا يَشْكُرُونَ",
    english: "A sign for them is the dead earth: We give it life and bring forth from it grain for them to eat. And We placed in it gardens of palms and grapevines, and caused springs to gush forth, so they may eat of its fruit. Will they not then give thanks?",
    source: "Yā Sīn 36:33–35",
    category: "provision",
    themes: ["gratitude", "creation"],
    editorialStatus: "published",
  },
  {
    id: "q:80:24-32",
    type: "quran",
    arabic: "فَلْيَنظُرِ ٱلْإِنسَـٰنُ إِلَىٰ طَعَامِهِۦٓ ۝ أَنَّا صَبَبْنَا ٱلْمَآءَ صَبًّا ۝ ثُمَّ شَقَقْنَا ٱلْأَرْضَ شَقًّا ۝ فَأَنۢبَتْنَا فِيهَا حَبًّا ۝ وَعِنَبًا وَقَضْبًا ۝ وَزَيْتُونًا وَنَخْلًا ۝ وَحَدَآئِقَ غُلْبًا ۝ وَفَـٰكِهَةً وَأَبًّا",
    english: "Let man consider his food: how We poured down water in abundance, then split the earth open, and caused grain to grow in it, and grapes and fresh vegetation, and olive trees and date palms, and dense gardens, and fruit and fodder.",
    source: "ʿAbasa 80:24–32",
    category: "provision",
    themes: ["reflection", "creation"],
    editorialStatus: "published",
  },
  {
    id: "q:2:168",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلنَّاسُ كُلُوا۟ مِمَّا فِى ٱلْأَرْضِ حَلَـٰلًا طَيِّبًا",
    english: "O humanity, eat from what is lawful and good on earth.",
    source: "Al-Baqarah 2:168",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "q:7:31",
    type: "quran",
    arabic: "كُلُوا۟ وَٱشْرَبُوا۟ وَلَا تُسْرِفُوٓا۟ ۚ إِنَّهُۥ لَا يُحِبُّ ٱلْمُسْرِفِينَ",
    english: "Eat and drink, but do not be excessive. He does not love the excessive.",
    source: "Al-Aʿrāf 7:31",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "q:23:21",
    type: "quran",
    arabic: "وَإِنَّ لَكُمْ فِى ٱلْأَنْعَـٰمِ لَعِبْرَةً ۖ نُّسْقِيكُم مِّمَّا فِى بُطُونِهَا وَلَكُمْ فِيهَا مَنَـٰفِعُ كَثِيرَةٌ وَمِنْهَا تَأْكُلُونَ",
    english: "And in livestock there is a lesson for you. We give you drink from what is in their bellies, and you have in them many benefits, and from them you eat.",
    source: "Al-Muʼminūn 23:21",
    category: "provision",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:16:11",
    type: "quran",
    arabic: "يُنۢبِتُ لَكُم بِهِ ٱلزَّرْعَ وَٱلزَّيْتُونَ وَٱلنَّخِيلَ وَٱلْأَعْنَـٰبَ وَمِن كُلِّ ٱلثَّمَرَٰتِ ۗ إِنَّ فِى ذَٰلِكَ لَـَٔايَةً لِّقَوْمٍ يَتَفَكَّرُونَ",
    english: "With it He causes crops, olives, palms, grapevines, and every kind of fruit to grow for you. Surely in this is a sign for those who reflect.",
    source: "Al-Naḥl 16:11",
    category: "provision",
    themes: ["reflection", "creation"],
    editorialStatus: "published",
  },
  {
    id: "q:55:10-12",
    type: "quran",
    arabic: "وَٱلْأَرْضَ وَضَعَهَا لِلْأَنَامِ ۝ فِيهَا فَـٰكِهَةٌ وَٱلنَّخْلُ ذَاتُ ٱلْأَكْمَامِ ۝ وَٱلْحَبُّ ذُو ٱلْعَصْفِ وَٱلرَّيْحَانُ",
    english: "And the earth He laid out for all living beings, with fruit and palm trees with date-stalks, and grain with husks and fragrant herbs.",
    source: "Al-Raḥmān 55:10–12",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:2:172",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ كُلُوا۟ مِن طَيِّبَـٰتِ مَا رَزَقْنَـٰكُمْ وَٱشْكُرُوا۟ لِلَّهِ إِن كُنتُمْ إِيَّاهُ تَعْبُدُونَ",
    english: "O believers, eat of the good things We have provided for you, and give thanks to Allah — if it is Him you truly worship.",
    source: "Al-Baqarah 2:172",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "q:14:32",
    type: "quran",
    arabic: "ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضَ وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءً فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًا لَّكُمْ",
    english: "Allah is the One who created the heavens and the earth, and sent down water from the sky, producing fruits thereby as provision for you.",
    source: "Ibrāhīm 14:32",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:16:114",
    type: "quran",
    arabic: "فَكُلُوا۟ مِمَّا رَزَقَكُمُ ٱللَّهُ حَلَـٰلًا طَيِّبًا وَٱشْكُرُوا۟ نِعْمَتَ ٱللَّهِ إِن كُنتُمْ إِيَّاهُ تَعْبُدُونَ",
    english: "So eat of the lawful and good things which Allah has provided for you, and be grateful for Allah's blessings, if it is Him you worship.",
    source: "Al-Naḥl 16:114",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "q:20:81",
    type: "quran",
    arabic: "كُلُوا۟ مِن طَيِّبَـٰتِ مَا رَزَقْنَـٰكُمْ وَلَا تَطْغَوْا۟ فِيهِ",
    english: "Eat of the good things We have provided for you, but do not transgress in them.",
    source: "Ṭā Hā 20:81",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "q:67:15",
    type: "quran",
    arabic: "هُوَ ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ ذَلُولًا فَٱمْشُوا۟ فِى مَنَاكِبِهَا وَكُلُوا۟ مِن رِّزْقِهِۦ ۖ وَإِلَيْهِ ٱلنُّشُورُ",
    english: "It is He who made the earth manageable for you — so walk along its slopes and eat of His provision. And to Him is the resurrection.",
    source: "Al-Mulk 67:15",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:56:63-65",
    type: "quran",
    arabic: "أَفَرَءَيْتُم مَّا تَحْرُثُونَ ۝ ءَأَنتُمْ تَزْرَعُونَهُۥٓ أَمْ نَحْنُ ٱلزَّٰرِعُونَ",
    english: "Have you considered what you sow? Is it you who cause it to grow, or are We the grower?",
    source: "Al-Wāqiʿah 56:63–64",
    category: "provision",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:56:68-70",
    type: "quran",
    arabic: "أَفَرَءَيْتُمُ ٱلْمَآءَ ٱلَّذِى تَشْرَبُونَ ۝ ءَأَنتُمْ أَنزَلْتُمُوهُ مِنَ ٱلْمُزْنِ أَمْ نَحْنُ ٱلْمُنزِلُونَ",
    english: "Have you considered the water you drink? Is it you who brought it down from the clouds, or is it We who bring it down?",
    source: "Al-Wāqiʿah 56:68–69",
    category: "provision",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:35:12",
    type: "quran",
    arabic: "وَمِن كُلٍّ تَأْكُلُونَ لَحْمًا طَرِيًّا وَتَسْتَخْرِجُونَ حِلْيَةً تَلْبَسُونَهَا",
    english: "And from each you eat tender meat and extract ornaments to wear.",
    source: "Fāṭir 35:12",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:16:5-7",
    type: "quran",
    arabic: "وَٱلْأَنْعَـٰمَ خَلَقَهَا ۗ لَكُمْ فِيهَا دِفْءٌ وَمَنَـٰفِعُ وَمِنْهَا تَأْكُلُونَ",
    english: "And He created livestock for you — in them is warmth, and many benefits, and from them you eat.",
    source: "Al-Naḥl 16:5",
    category: "provision",
    themes: ["creation"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Prophetic foods and nutrition ═══

  {
    id: "h:bukhari:5431",
    type: "hadith",
    arabic: "نِعْمَ الإِدَامُ الْخَلُّ",
    english: "What an excellent condiment vinegar is.",
    source: "Ṣaḥīḥ Muslim 2051",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5440",
    type: "hadith",
    arabic: "الْبَرَكَةُ فِي ثَلاَثَةٍ فِي الْجَمَاعَةِ وَالثَّرِيدِ وَالسَّحُورِ",
    english: "Blessing is in three things: the congregation, the tharīd, and the pre-dawn meal.",
    source: "Sunan al-Nasāʼī · Graded Ḥasan",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5445",
    type: "hadith",
    arabic: "مَنْ تَصَبَّحَ كُلَّ يَوْمٍ سَبْعَ تَمَرَاتٍ عَجْوَةً لَمْ يَضُرَّهُ فِي ذَلِكَ الْيَوْمِ سُمٌّ وَلاَ سِحْرٌ",
    english: "Whoever eats seven ʿajwah dates each morning will not be harmed that day by poison or magic.",
    source: "Ṣaḥīḥ Muslim 2047",
    category: "provision",
    themes: ["healing"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2049",
    type: "hadith",
    arabic: "بَيْتٌ لاَ تَمْرَ فِيهِ جِيَاعٌ أَهْلُهُ",
    english: "A house without dates is a house whose people are hungry.",
    source: "Ṣaḥīḥ Muslim 2046",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:1851",
    type: "hadith",
    arabic: "كُلُوا الزَّيْتَ وَادَّهِنُوا بِهِ فَإِنَّهُ مِنْ شَجَرَةٍ مُبَارَكَةٍ",
    english: "Eat olive oil and anoint yourselves with it, for it comes from a blessed tree.",
    source: "Sunan al-Tirmidhī 1851 · Graded Ṣaḥīḥ",
    category: "provision",
    themes: ["healing"],
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2380",
    type: "hadith",
    arabic: "مَا مَلأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ بِحَسْبِ ابْنِ آدَمَ أُكُلاَتٌ يُقِمْنَ صُلْبَهُ فَإِنْ كَانَ لاَ مَحَالَةَ فَثُلُثٌ لِطَعَامِهِ وَثُلُثٌ لِشَرَابِهِ وَثُلُثٌ لِنَفَسِهِ",
    english: "The son of Ādam fills no vessel worse than his stomach. A few morsels are sufficient to keep his back straight. But if he must eat more, then a third for his food, a third for his drink, and a third for his breath.",
    source: "Sunan al-Tirmidhī 2380 · Graded Ṣaḥīḥ",
    category: "provision",
    themes: ["healing"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2033",
    type: "hadith",
    arabic: "سَمُّوا اللَّهَ وَكُلُوا بِيَمِينِكُمْ وَكُلُوا مِمَّا يَلِيكُمْ",
    english: "Mention the name of Allah, eat with your right hand, and eat from what is nearest to you.",
    source: "Ṣaḥīḥ al-Bukhārī 5376",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5376",
    type: "hadith",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    english: "All praise is due to Allah, who fed me this and provided it for me without any effort or power on my part.",
    source: "Sunan Abī Dāwūd 4023 · Graded Ḥasan",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:5398",
    type: "hadith",
    arabic: "مَا عَابَ رَسُولُ اللَّهِ صلى الله عليه وسلم طَعَامًا قَطُّ إِنِ اشْتَهَاهُ أَكَلَهُ وَإِنْ كَرِهَهُ تَرَكَهُ",
    english: "The Messenger of Allah ﷺ never criticised any food. If he desired it he ate it, and if he disliked it he left it.",
    source: "Ṣaḥīḥ al-Bukhārī 5409",
    category: "provision",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2029",
    type: "hadith",
    arabic: "إِذَا أَكَلَ أَحَدُكُمْ فَلْيَأْكُلْ بِيَمِينِهِ وَإِذَا شَرِبَ فَلْيَشْرَبْ بِيَمِينِهِ",
    english: "When one of you eats, let him eat with his right hand, and when he drinks, let him drink with his right hand.",
    source: "Ṣaḥīḥ Muslim 2020",
    category: "provision",
    editorialStatus: "published",
  },

  // ═══ Qur'anic — Sustenance and provision ═══

  {
    id: "q:29:60",
    type: "quran",
    arabic: "وَكَأَيِّن مِّن دَآبَّةٍ لَّا تَحْمِلُ رِزْقَهَا ٱللَّهُ يَرْزُقُهَا وَإِيَّاكُمْ ۚ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ",
    english: "How many a creature does not carry its own provision — Allah provides for it and for you. He is the All-Hearing, the All-Knowing.",
    source: "Al-ʿAnkabūt 29:60",
    category: "provision",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:11:6",
    type: "quran",
    arabic: "وَمَا مِن دَآبَّةٍ فِى ٱلْأَرْضِ إِلَّا عَلَى ٱللَّهِ رِزْقُهَا",
    english: "There is no creature on earth whose provision is not guaranteed by Allah.",
    source: "Hūd 11:6",
    category: "provision",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:51:58",
    type: "quran",
    arabic: "إِنَّ ٱللَّهَ هُوَ ٱلرَّزَّاقُ ذُو ٱلْقُوَّةِ ٱلْمَتِينُ",
    english: "Indeed, it is Allah who is the Provider, the Firm Possessor of strength.",
    source: "Al-Dhāriyāt 51:58",
    category: "provision",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:65:2-3",
    type: "quran",
    arabic: "وَمَن يَتَّقِ ٱللَّهَ يَجْعَل لَّهُۥ مَخْرَجًا ۝ وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ",
    english: "And whoever is mindful of Allah, He will make a way out for them, and provide for them from sources they could never imagine.",
    source: "Al-Ṭalāq 65:2–3",
    category: "provision",
    themes: ["trust"],
    editorialStatus: "published",
  },
  {
    id: "q:17:70",
    type: "quran",
    arabic: "وَلَقَدْ كَرَّمْنَا بَنِىٓ ءَادَمَ وَحَمَلْنَـٰهُمْ فِى ٱلْبَرِّ وَٱلْبَحْرِ وَرَزَقْنَـٰهُم مِّنَ ٱلطَّيِّبَـٰتِ",
    english: "We have honoured the children of Ādam and carried them on land and sea, and provided them with good things.",
    source: "Al-Isrāʼ 17:70",
    category: "provision",
    themes: ["mercy"],
    editorialStatus: "published",
  },

  // ═══ Hadith — Moderation and contentment ═══

  {
    id: "h:tirmidhi:2346",
    type: "hadith",
    arabic: "مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ مُعَافًى فِي جَسَدِهِ عِنْدَهُ قُوتُ يَوْمِهِ فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا",
    english: "Whoever among you wakes up secure in his dwelling, healthy in his body, and has his provision for the day — it is as if the whole world has been gathered for him.",
    source: "Sunan al-Tirmidhī 2346 · Graded Ḥasan",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:1054",
    type: "hadith",
    arabic: "لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ",
    english: "Richness is not having many possessions, but richness is the richness of the soul.",
    source: "Ṣaḥīḥ al-Bukhārī 6446",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6427",
    type: "hadith",
    arabic: "انْظُرُوا إِلَى مَنْ أَسْفَلَ مِنْكُمْ وَلاَ تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ فَهُوَ أَجْدَرُ أَنْ لاَ تَزْدَرُوا نِعْمَةَ اللَّهِ",
    english: "Look at those below you and do not look at those above you, for it is more likely that you will not belittle the blessings of Allah.",
    source: "Ṣaḥīḥ Muslim 2963",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6412",
    type: "hadith",
    arabic: "قَدْ أَفْلَحَ مَنْ أَسْلَمَ وَرُزِقَ كَفَافًا وَقَنَّعَهُ اللَّهُ بِمَا آتَاهُ",
    english: "He has succeeded who has submitted to Allah, been given sufficient provision, and been made content by Allah with what he was given.",
    source: "Ṣaḥīḥ Muslim 1054",
    category: "provision",
    themes: ["gratitude"],
    editorialStatus: "published",
  },
];
