import type { RevelationEntry } from "../../schema";

/**
 * Theme: Purification (التزكية)
 *
 * The soul, repentance, character, sincerity,
 * and the inner life of the believer.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const purificationCollection: RevelationEntry[] = [
  {
    id: "q:91:7-10",
    type: "quran",
    arabic: "وَنَفْسٍ وَمَا سَوَّىٰهَا ۝ فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَىٰهَا ۝ قَدْ أَفْلَحَ مَن زَكَّىٰهَا ۝ وَقَدْ خَابَ مَن دَسَّىٰهَا",
    english: "And by the soul and the One who proportioned it, then inspired it with its wickedness and its righteousness — truly successful is the one who purifies it, and truly failed is the one who corrupts it.",
    source: "Al-Shams 91:7–10",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "q:87:14-15",
    type: "quran",
    arabic: "قَدْ أَفْلَحَ مَن تَزَكَّىٰ ۝ وَذَكَرَ ٱسْمَ رَبِّهِۦ فَصَلَّىٰ",
    english: "Truly successful is the one who purifies himself, remembers the name of his Lord, and prays.",
    source: "Al-Aʿlā 87:14–15",
    category: "purification",
    themes: ["supplication"],
    editorialStatus: "published",
  },
  {
    id: "q:2:222",
    type: "quran",
    arabic: "إِنَّ ٱللَّهَ يُحِبُّ ٱلتَّوَّٰبِينَ وَيُحِبُّ ٱلْمُتَطَهِّرِينَ",
    english: "Indeed, Allah loves those who repent and loves those who purify themselves.",
    source: "Al-Baqarah 2:222",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "q:20:82",
    type: "quran",
    arabic: "وَإِنِّى لَغَفَّارٌ لِّمَن تَابَ وَءَامَنَ وَعَمِلَ صَـٰلِحًا ثُمَّ ٱهْتَدَىٰ",
    english: "And I am indeed Most Forgiving to whoever repents, believes, and does righteous work, then continues on guidance.",
    source: "Ṭā Hā 20:82",
    category: "purification",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:66:8",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ تُوبُوٓا۟ إِلَى ٱللَّهِ تَوْبَةً نَّصُوحًا",
    english: "O believers, repent to Allah with a sincere repentance.",
    source: "Al-Taḥrīm 66:8",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "q:3:135",
    type: "quran",
    arabic: "وَٱلَّذِينَ إِذَا فَعَلُوا۟ فَـٰحِشَةً أَوْ ظَلَمُوٓا۟ أَنفُسَهُمْ ذَكَرُوا۟ ٱللَّهَ فَٱسْتَغْفَرُوا۟ لِذُنُوبِهِمْ ۗ وَمَن يَغْفِرُ ٱلذُّنُوبَ إِلَّا ٱللَّهُ",
    english: "And those who, when they commit an indecency or wrong themselves, remember Allah and seek forgiveness for their sins — and who forgives sins but Allah?",
    source: "Āl ʿImrān 3:135",
    category: "purification",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:49:13",
    type: "quran",
    arabic: "إِنَّ أَكْرَمَكُمْ عِندَ ٱللَّهِ أَتْقَىٰكُمْ",
    english: "Indeed, the most honourable of you before Allah is the most righteous among you.",
    source: "Al-Ḥujurāt 49:13",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "q:59:18",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱتَّقُوا۟ ٱللَّهَ وَلْتَنظُرْ نَفْسٌ مَّا قَدَّمَتْ لِغَدٍ",
    english: "O believers, be mindful of Allah, and let every soul consider what it has sent forth for tomorrow.",
    source: "Al-Ḥashr 59:18",
    category: "purification",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:24:30",
    type: "quran",
    arabic: "ذَٰلِكَ أَزْكَىٰ لَهُمْ ۗ إِنَّ ٱللَّهَ خَبِيرٌۢ بِمَا يَصْنَعُونَ",
    english: "That is purer for them. Indeed, Allah is fully aware of what they do.",
    source: "Al-Nūr 24:30",
    category: "purification",
    editorialStatus: "published",
  },

  // ═══ Hadith — Purification and character ═══

  {
    id: "h:muslim:223",
    type: "hadith",
    arabic: "الطَّهُورُ شَطْرُ الإِيمَانِ",
    english: "Purification is half of faith.",
    source: "Ṣaḥīḥ Muslim 223",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6094",
    type: "hadith",
    arabic: "إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ",
    english: "Truthfulness leads to righteousness, and righteousness leads to Paradise.",
    source: "Ṣaḥīḥ al-Bukhārī 6094",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2003",
    type: "hadith",
    arabic: "إِنَّمَا بُعِثْتُ لِأُتَمِّمَ صَالِحَ الأَخْلاَقِ",
    english: "I was sent to perfect good character.",
    source: "Muwaṭṭaʼ Mālik · Graded Ṣaḥīḥ",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6116",
    type: "hadith",
    arabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    english: "The strong person is not the one who can wrestle others to the ground. The strong person is the one who controls himself when angry.",
    source: "Ṣaḥīḥ al-Bukhārī 6114",
    category: "purification",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2564",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    english: "Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.",
    source: "Ṣaḥīḥ Muslim 2564",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:13",
    type: "hadith",
    arabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    english: "None of you truly believes until he loves for his brother what he loves for himself.",
    source: "Ṣaḥīḥ al-Bukhārī 13",
    category: "purification",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2553",
    type: "hadith",
    arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ",
    english: "Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.",
    source: "Sunan al-Tirmidhī 1987 · Graded Ḥasan",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2002",
    type: "hadith",
    arabic: "أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا",
    english: "The most complete of the believers in faith is the best of them in character.",
    source: "Sunan Abī Dāwūd 4682 · Graded Ṣaḥīḥ",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:2442",
    type: "hadith",
    arabic: "انْصُرْ أَخَاكَ ظَالِمًا أَوْ مَظْلُومًا",
    english: "Support your brother whether he is an oppressor or is oppressed.",
    source: "Ṣaḥīḥ al-Bukhārī 2444",
    category: "purification",
    themes: ["mercy"],
    editorialStatus: "published",
    scholarNotes: "When asked how to support the oppressor, the Prophet ﷺ said: 'By restraining him from oppression.'",
  },
  {
    id: "h:bukhari:6018",
    type: "hadith",
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    english: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
    source: "Ṣaḥīḥ al-Bukhārī 6018",
    category: "purification",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2607",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلاً أَنْ يُتْقِنَهُ",
    english: "Allah loves that when one of you does something, he does it with excellence.",
    source: "Musnad al-Bazzār · Graded Ḥasan by al-Albānī",
    category: "purification",
    editorialStatus: "published",
  },
];
