import type { RevelationEntry } from "../../schema";

/**
 * Theme: Reflection (التفكر)
 *
 * Contemplation of creation, pondering the Qur'an,
 * and signs that invite the intellect.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const reflectionCollection: RevelationEntry[] = [
  {
    id: "q:3:190-191",
    type: "quran",
    arabic: "إِنَّ فِى خَلْقِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَـٰفِ ٱلَّيْلِ وَٱلنَّهَارِ لَـَٔايَـٰتٍ لِّأُو۟لِى ٱلْأَلْبَـٰبِ ۝ ٱلَّذِينَ يَذْكُرُونَ ٱللَّهَ قِيَـٰمًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِى خَلْقِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ رَبَّنَا مَا خَلَقْتَ هَـٰذَا بَـٰطِلًا",
    english: "In the creation of the heavens and the earth, and the alternation of night and day, there are truly signs for people of understanding — who remember Allah standing, sitting, and on their sides, and reflect upon the creation of the heavens and the earth, saying: 'Our Lord, You have not created this in vain.'",
    source: "Āl ʿImrān 3:190–191",
    category: "reflection",
    themes: ["supplication", "creation"],
    editorialStatus: "published",
  },
  {
    id: "q:47:24",
    type: "quran",
    arabic: "أَفَلَا يَتَدَبَّرُونَ ٱلْقُرْءَانَ أَمْ عَلَىٰ قُلُوبٍ أَقْفَالُهَآ",
    english: "Do they not reflect upon the Qur'an, or are there locks upon their hearts?",
    source: "Muḥammad 47:24",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:51:20-21",
    type: "quran",
    arabic: "وَفِى ٱلْأَرْضِ ءَايَـٰتٌ لِّلْمُوقِنِينَ ۝ وَفِىٓ أَنفُسِكُمْ ۚ أَفَلَا تُبْصِرُونَ",
    english: "And on earth there are signs for those with sure faith — and in yourselves. Do you not see?",
    source: "Al-Dhāriyāt 51:20–21",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:4:82",
    type: "quran",
    arabic: "أَفَلَا يَتَدَبَّرُونَ ٱلْقُرْءَانَ ۚ وَلَوْ كَانَ مِنْ عِندِ غَيْرِ ٱللَّهِ لَوَجَدُوا۟ فِيهِ ٱخْتِلَـٰفًا كَثِيرًا",
    english: "Do they not reflect upon the Qur'an? Had it been from other than Allah, they would have found in it much contradiction.",
    source: "Al-Nisāʼ 4:82",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:88:17-20",
    type: "quran",
    arabic: "أَفَلَا يَنظُرُونَ إِلَى ٱلْإِبِلِ كَيْفَ خُلِقَتْ ۝ وَإِلَى ٱلسَّمَآءِ كَيْفَ رُفِعَتْ ۝ وَإِلَى ٱلْجِبَالِ كَيْفَ نُصِبَتْ ۝ وَإِلَى ٱلْأَرْضِ كَيْفَ سُطِحَتْ",
    english: "Do they not look at the camels — how they are created? And at the sky — how it is raised? And at the mountains — how they are set? And at the earth — how it is spread out?",
    source: "Al-Ghāshiyah 88:17–20",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:10:101",
    type: "quran",
    arabic: "قُلِ ٱنظُرُوا۟ مَاذَا فِى ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ",
    english: "Say: observe what is in the heavens and the earth.",
    source: "Yūnus 10:101",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:2:164",
    type: "quran",
    arabic: "إِنَّ فِى خَلْقِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَـٰفِ ٱلَّيْلِ وَٱلنَّهَارِ وَٱلْفُلْكِ ٱلَّتِى تَجْرِى فِى ٱلْبَحْرِ بِمَا يَنفَعُ ٱلنَّاسَ وَمَآ أَنزَلَ ٱللَّهُ مِنَ ٱلسَّمَآءِ مِن مَّآءٍ فَأَحْيَا بِهِ ٱلْأَرْضَ بَعْدَ مَوْتِهَا وَبَثَّ فِيهَا مِن كُلِّ دَآبَّةٍ وَتَصْرِيفِ ٱلرِّيَـٰحِ وَٱلسَّحَابِ ٱلْمُسَخَّرِ بَيْنَ ٱلسَّمَآءِ وَٱلْأَرْضِ لَـَٔايَـٰتٍ لِّقَوْمٍ يَعْقِلُونَ",
    english: "Indeed, in the creation of the heavens and the earth; the alternation of night and day; the ships that sail the sea for the benefit of people; the water sent down by Allah from the sky, reviving the earth after its death; the spreading of all kinds of creatures; the shifting of winds and clouds between the sky and earth — in all of this are signs for people of understanding.",
    source: "Al-Baqarah 2:164",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:30:21",
    type: "quran",
    arabic: "وَمِنْ ءَايَـٰتِهِۦٓ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَٰجًا لِّتَسْكُنُوٓا۟ إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً ۚ إِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍ لِّقَوْمٍ يَتَفَكَّرُونَ",
    english: "And among His signs is that He created for you spouses from among yourselves, so that you may find tranquillity in them, and He placed between you love and mercy. In this are signs for those who reflect.",
    source: "Al-Rūm 30:21",
    category: "reflection",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:30:22",
    type: "quran",
    arabic: "وَمِنْ ءَايَـٰتِهِۦ خَلْقُ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَـٰفُ أَلْسِنَتِكُمْ وَأَلْوَٰنِكُمْ ۚ إِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍ لِّلْعَـٰلِمِينَ",
    english: "And among His signs is the creation of the heavens and the earth, and the diversity of your languages and colours. In this are signs for those of knowledge.",
    source: "Al-Rūm 30:22",
    category: "reflection",
    themes: ["creation", "knowledge"],
    editorialStatus: "published",
  },
  {
    id: "q:59:21",
    type: "quran",
    arabic: "لَوْ أَنزَلْنَا هَـٰذَا ٱلْقُرْءَانَ عَلَىٰ جَبَلٍ لَّرَأَيْتَهُۥ خَـٰشِعًا مُّتَصَدِّعًا مِّنْ خَشْيَةِ ٱللَّهِ ۚ وَتِلْكَ ٱلْأَمْثَـٰلُ نَضْرِبُهَا لِلنَّاسِ لَعَلَّهُمْ يَتَفَكَّرُونَ",
    english: "Had We sent down this Qur'an upon a mountain, you would have seen it humbled and splitting apart from the fear of Allah. These are the parables We set forth for people, so that they may reflect.",
    source: "Al-Ḥashr 59:21",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:6:50",
    type: "quran",
    arabic: "أَفَلَا تَتَفَكَّرُونَ",
    english: "Will you not then reflect?",
    source: "Al-Anʿām 6:50",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:16:17",
    type: "quran",
    arabic: "أَفَمَن يَخْلُقُ كَمَن لَّا يَخْلُقُ ۗ أَفَلَا تَذَكَّرُونَ",
    english: "Is the One who creates equal to those who do not create? Will you not then be mindful?",
    source: "Al-Naḥl 16:17",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:45:13",
    type: "quran",
    arabic: "وَسَخَّرَ لَكُم مَّا فِى ٱلسَّمَـٰوَٰتِ وَمَا فِى ٱلْأَرْضِ جَمِيعًا مِّنْهُ ۚ إِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍ لِّقَوْمٍ يَتَفَكَّرُونَ",
    english: "And He has subjected to you all that is in the heavens and all that is on earth — all from Him. In this are signs for a people who reflect.",
    source: "Al-Jāthiyah 45:13",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:39:42",
    type: "quran",
    arabic: "ٱللَّهُ يَتَوَفَّى ٱلْأَنفُسَ حِينَ مَوْتِهَا وَٱلَّتِى لَمْ تَمُتْ فِى مَنَامِهَا ۖ فَيُمْسِكُ ٱلَّتِى قَضَىٰ عَلَيْهَا ٱلْمَوْتَ وَيُرْسِلُ ٱلْأُخْرَىٰٓ إِلَىٰٓ أَجَلٍ مُّسَمًّى ۚ إِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍ لِّقَوْمٍ يَتَفَكَّرُونَ",
    english: "Allah takes the souls at the time of their death, and those that have not died during their sleep. He retains those for which He has decreed death and releases the others until an appointed time. In this are signs for a people who reflect.",
    source: "Al-Zumar 39:42",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "q:7:185",
    type: "quran",
    arabic: "أَوَلَمْ يَنظُرُوا۟ فِى مَلَكُوتِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ وَمَا خَلَقَ ٱللَّهُ مِن شَىْءٍ",
    english: "Have they not looked into the realm of the heavens and the earth and everything that Allah has created?",
    source: "Al-Aʿrāf 7:185",
    category: "reflection",
    themes: ["creation"],
    editorialStatus: "published",
  },
  {
    id: "q:23:115",
    type: "quran",
    arabic: "أَفَحَسِبْتُمْ أَنَّمَا خَلَقْنَـٰكُمْ عَبَثًا وَأَنَّكُمْ إِلَيْنَا لَا تُرْجَعُونَ",
    english: "Did you think We created you without purpose, and that you would not be brought back to Us?",
    source: "Al-Muʼminūn 23:115",
    category: "reflection",
    editorialStatus: "published",
  },

  // ═══ Hadith — Reflection ═══

  {
    id: "h:tabarani:reflection:1",
    type: "hadith",
    arabic: "تَفَكَّرُوا فِي آلَاءِ اللَّهِ وَلَا تَتَفَكَّرُوا فِي اللَّهِ",
    english: "Reflect upon the blessings of Allah, but do not attempt to reflect upon the essence of Allah.",
    source: "Al-Muʿjam al-Awsaṭ · al-Ṭabarānī · Graded Ḥasan by al-Albānī",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6491",
    type: "hadith",
    arabic: "إِنَّ اللَّهَ كَتَبَ الْحَسَنَاتِ وَالسَّيِّئَاتِ ثُمَّ بَيَّنَ ذَلِكَ فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ لَهُ عِنْدَهُ حَسَنَةً كَامِلَةً",
    english: "Allah has recorded good deeds and bad deeds. Whoever intends a good deed but does not do it, Allah records it as a complete good deed.",
    source: "Ṣaḥīḥ al-Bukhārī 6491",
    category: "reflection",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:52",
    type: "hadith",
    arabic: "أَلاَ وَإِنَّ فِي الْجَسَدِ مُضْغَةً إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ أَلاَ وَهِيَ الْقَلْبُ",
    english: "Indeed, in the body there is a morsel of flesh — if it is sound, the whole body is sound; and if it is corrupt, the whole body is corrupt. It is the heart.",
    source: "Ṣaḥīḥ al-Bukhārī 52",
    category: "reflection",
    themes: ["purification"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6412b",
    type: "hadith",
    arabic: "كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ",
    english: "Be in this world as if you were a stranger or a traveller.",
    source: "Ṣaḥīḥ al-Bukhārī 6416",
    category: "reflection",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2317",
    type: "hadith",
    arabic: "كَفَى بِالْمَوْتِ وَاعِظًا",
    english: "Death is sufficient as an admonisher.",
    source: "Sunan al-Nasāʼī · Graded Ḥasan",
    category: "reflection",
    editorialStatus: "published",
  },
];
