import type { RevelationEntry } from "../../schema";

/**
 * Theme: Supplication (الدعاء)
 *
 * Prayers, remembrance of Allah (dhikr),
 * and the nearness of Allah to those who call upon Him.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const supplicationCollection: RevelationEntry[] = [
  {
    id: "q:2:186",
    type: "quran",
    arabic: "وَإِذَا سَأَلَكَ عِبَادِى عَنِّى فَإِنِّى قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ ٱلدَّاعِ إِذَا دَعَانِ",
    english: "And when My servants ask you about Me — I am near. I respond to the call of the caller when he calls upon Me.",
    source: "Al-Baqarah 2:186",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:40:60",
    type: "quran",
    arabic: "وَقَالَ رَبُّكُمُ ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ",
    english: "And your Lord says: call upon Me, I will respond to you.",
    source: "Ghāfir 40:60",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:13:28",
    type: "quran",
    arabic: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ",
    english: "Truly it is in the remembrance of Allah that hearts find peace.",
    source: "Al-Raʿd 13:28",
    category: "supplication",
    themes: ["healing"],
    editorialStatus: "published",
  },
  {
    id: "q:33:41-42",
    type: "quran",
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱذْكُرُوا۟ ٱللَّهَ ذِكْرًا كَثِيرًا ۝ وَسَبِّحُوهُ بُكْرَةً وَأَصِيلًا",
    english: "O believers, remember Allah often, and glorify Him morning and evening.",
    source: "Al-Aḥzāb 33:41–42",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:7:55",
    type: "quran",
    arabic: "ٱدْعُوا۟ رَبَّكُمْ تَضَرُّعًا وَخُفْيَةً ۚ إِنَّهُۥ لَا يُحِبُّ ٱلْمُعْتَدِينَ",
    english: "Call upon your Lord humbly and privately. He does not love the transgressors.",
    source: "Al-Aʿrāf 7:55",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:7:180",
    type: "quran",
    arabic: "وَلِلَّهِ ٱلْأَسْمَآءُ ٱلْحُسْنَىٰ فَٱدْعُوهُ بِهَا",
    english: "And to Allah belong the most beautiful names, so call upon Him by them.",
    source: "Al-Aʿrāf 7:180",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:73:8",
    type: "quran",
    arabic: "وَٱذْكُرِ ٱسْمَ رَبِّكَ وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا",
    english: "And remember the name of your Lord, and devote yourself to Him wholeheartedly.",
    source: "Al-Muzzammil 73:8",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:50:16",
    type: "quran",
    arabic: "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ ٱلْوَرِيدِ",
    english: "And We are closer to him than his jugular vein.",
    source: "Qāf 50:16",
    category: "supplication",
    themes: ["reflection"],
    editorialStatus: "published",
  },
  {
    id: "q:2:201",
    type: "quran",
    arabic: "رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْـَٔاخِرَةِ حَسَنَةً وَقِنَا عَذَابَ ٱلنَّارِ",
    english: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
    source: "Al-Baqarah 2:201",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "q:3:8",
    type: "quran",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ ٱلْوَهَّابُ",
    english: "Our Lord, do not let our hearts deviate after You have guided us, and grant us mercy from Yourself. Indeed, You are the Bestower.",
    source: "Āl ʿImrān 3:8",
    category: "supplication",
    themes: ["mercy"],
    editorialStatus: "published",
  },
  {
    id: "q:25:74",
    type: "quran",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَٰجِنَا وَذُرِّيَّـٰتِنَا قُرَّةَ أَعْيُنٍ وَٱجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    english: "Our Lord, grant us from our spouses and offspring comfort to our eyes, and make us a model for the righteous.",
    source: "Al-Furqān 25:74",
    category: "supplication",
    editorialStatus: "published",
  },

  // ═══ Hadith — Supplication and remembrance ═══

  {
    id: "h:muslim:2675",
    type: "hadith",
    arabic: "أَنَا عِنْدَ ظَنِّ عَبْدِي بِي وَأَنَا مَعَهُ إِذَا ذَكَرَنِي",
    english: "I am as My servant expects Me to be, and I am with him when he remembers Me.",
    source: "Ṣaḥīḥ al-Bukhārī 7405",
    category: "supplication",
    editorialStatus: "published",
    scholarNotes: "A ḥadīth qudsī.",
  },
  {
    id: "h:tirmidhi:3370",
    type: "hadith",
    arabic: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    english: "Supplication is worship itself.",
    source: "Sunan Abī Dāwūd 1479 · Graded Ṣaḥīḥ",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:3371",
    type: "hadith",
    arabic: "إِنَّهُ مَنْ لَمْ يَسْأَلِ اللَّهَ يَغْضَبْ عَلَيْهِ",
    english: "He who does not ask Allah will incur His displeasure.",
    source: "Sunan al-Tirmidhī 3373 · Graded Ḥasan",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2735",
    type: "hadith",
    arabic: "مَنْ قَالَ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ حُطَّتْ خَطَايَاهُ وَإِنْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ",
    english: "Whoever says 'Subḥān Allāhi wa biḥamdih' (Glory be to Allah and praise Him) a hundred times a day will have his sins forgiven, even if they were like the foam of the sea.",
    source: "Ṣaḥīḥ al-Bukhārī 6405",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6306",
    type: "hadith",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    english: "O Allah, I seek refuge in You from anxiety and grief, from inability and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by others.",
    source: "Ṣaḥīḥ al-Bukhārī 6369",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2702",
    type: "hadith",
    arabic: "سَيِّدُ الاِسْتِغْفَارِ أَنْ تَقُولَ اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    english: "The master of seeking forgiveness is to say: 'O Allah, You are my Lord, there is no god but You. You created me and I am Your servant.'",
    source: "Ṣaḥīḥ al-Bukhārī 6306",
    category: "supplication",
    themes: ["purification"],
    editorialStatus: "published",
  },
  {
    id: "h:bukhari:6407",
    type: "hadith",
    arabic: "كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ ثَقِيلَتَانِ فِي الْمِيزَانِ حَبِيبَتَانِ إِلَى الرَّحْمَنِ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ",
    english: "Two words are light on the tongue, heavy on the scale, and beloved to the Most Merciful: Subḥān Allāhi wa biḥamdih, Subḥān Allāhi al-ʿAẓīm.",
    source: "Ṣaḥīḥ al-Bukhārī 6406",
    category: "supplication",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2691",
    type: "hadith",
    arabic: "أَحَبُّ الْكَلاَمِ إِلَى اللَّهِ أَرْبَعٌ سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلاَ إِلَهَ إِلاَّ اللَّهُ وَاللَّهُ أَكْبَرُ",
    english: "The most beloved words to Allah are four: Subḥān Allāh, Al-ḥamdu lillāh, Lā ilāha illā Allāh, Allāhu Akbar.",
    source: "Ṣaḥīḥ Muslim 2137",
    category: "supplication",
    editorialStatus: "published",
  },
];
