import type { RevelationEntry } from "../../schema";

/**
 * Theme: Trust (التوكل)
 *
 * Reliance upon Allah, certainty in His decree,
 * and the balance between effort and surrender.
 *
 * Sources verified against Quran.com and Sunnah.com.
 * Hadith are Sahih or Hasan only.
 */
export const trustCollection: RevelationEntry[] = [
  {
    id: "q:3:159",
    type: "quran",
    arabic: "فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى ٱللَّهِ ۚ إِنَّ ٱللَّهَ يُحِبُّ ٱلْمُتَوَكِّلِينَ",
    english: "And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely upon Him.",
    source: "Āl ʿImrān 3:159",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:65:3",
    type: "quran",
    arabic: "وَمَن يَتَوَكَّلْ عَلَى ٱللَّهِ فَهُوَ حَسْبُهُۥ ۚ إِنَّ ٱللَّهَ بَـٰلِغُ أَمْرِهِۦ ۚ قَدْ جَعَلَ ٱللَّهُ لِكُلِّ شَىْءٍ قَدْرًا",
    english: "And whoever relies upon Allah — He is sufficient for him. Indeed, Allah will accomplish His purpose. He has already set a measure for everything.",
    source: "Al-Ṭalāq 65:3",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:9:51",
    type: "quran",
    arabic: "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا هُوَ مَوْلَىٰنَا ۚ وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ",
    english: "Say: nothing will befall us except what Allah has decreed for us. He is our Protector. And upon Allah let the believers rely.",
    source: "Al-Tawbah 9:51",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:8:2",
    type: "quran",
    arabic: "إِنَّمَا ٱلْمُؤْمِنُونَ ٱلَّذِينَ إِذَا ذُكِرَ ٱللَّهُ وَجِلَتْ قُلُوبُهُمْ وَإِذَا تُلِيَتْ عَلَيْهِمْ ءَايَـٰتُهُۥ زَادَتْهُمْ إِيمَـٰنًا وَعَلَىٰ رَبِّهِمْ يَتَوَكَّلُونَ",
    english: "True believers are only those whose hearts tremble at the mention of Allah, whose faith increases when His verses are recited to them, and who put their trust in their Lord.",
    source: "Al-Anfāl 8:2",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:14:12",
    type: "quran",
    arabic: "وَمَا لَنَآ أَلَّا نَتَوَكَّلَ عَلَى ٱللَّهِ وَقَدْ هَدَىٰنَا سُبُلَنَا ۚ وَلَنَصْبِرَنَّ عَلَىٰ مَآ ءَاذَيْتُمُونَا ۚ وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُتَوَكِّلُونَ",
    english: "And why should we not put our trust in Allah when He has guided us to our ways? We will certainly bear patiently whatever harm you cause us. And in Allah let the trusting put their trust.",
    source: "Ibrāhīm 14:12",
    category: "trust",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "q:33:3",
    type: "quran",
    arabic: "وَتَوَكَّلْ عَلَى ٱللَّهِ ۚ وَكَفَىٰ بِٱللَّهِ وَكِيلًا",
    english: "And put your trust in Allah. Allah is sufficient as a Trustee.",
    source: "Al-Aḥzāb 33:3",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:57:22-23",
    type: "quran",
    arabic: "مَآ أَصَابَ مِن مُّصِيبَةٍ فِى ٱلْأَرْضِ وَلَا فِىٓ أَنفُسِكُمْ إِلَّا فِى كِتَـٰبٍ مِّن قَبْلِ أَن نَّبْرَأَهَآ ۚ إِنَّ ذَٰلِكَ عَلَى ٱللَّهِ يَسِيرٌ ۝ لِّكَيْلَا تَأْسَوْا۟ عَلَىٰ مَا فَاتَكُمْ وَلَا تَفْرَحُوا۟ بِمَآ ءَاتَىٰكُمْ",
    english: "No disaster strikes upon the earth or among yourselves except that it is in a record before We bring it into being. That is easy for Allah — so that you may not grieve over what you have lost, nor exult over what He has given you.",
    source: "Al-Ḥadīd 57:22–23",
    category: "trust",
    themes: ["patience"],
    editorialStatus: "published",
  },
  {
    id: "q:64:11",
    type: "quran",
    arabic: "مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذْنِ ٱللَّهِ ۗ وَمَن يُؤْمِنۢ بِٱللَّهِ يَهْدِ قَلْبَهُۥ",
    english: "No disaster strikes except by the permission of Allah. And whoever believes in Allah, He will guide his heart.",
    source: "Al-Taghābun 64:11",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:4:78",
    type: "quran",
    arabic: "قُلْ كُلٌّ مِّنْ عِندِ ٱللَّهِ",
    english: "Say: all is from Allah.",
    source: "Al-Nisāʼ 4:78",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:39:38",
    type: "quran",
    arabic: "قُلْ حَسْبِىَ ٱللَّهُ ۖ عَلَيْهِ يَتَوَكَّلُ ٱلْمُتَوَكِّلُونَ",
    english: "Say: Allah is sufficient for me. In Him the trusting put their trust.",
    source: "Al-Zumar 39:38",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "q:11:88",
    type: "quran",
    arabic: "وَمَا تَوْفِيقِىٓ إِلَّا بِٱللَّهِ ۚ عَلَيْهِ تَوَكَّلْتُ وَإِلَيْهِ أُنِيبُ",
    english: "My success is only through Allah. In Him I trust, and to Him I turn.",
    source: "Hūd 11:88",
    category: "trust",
    editorialStatus: "published",
  },

  // ═══ Hadith — Trust ═══

  {
    id: "h:tirmidhi:2517",
    type: "hadith",
    arabic: "لَوْ أَنَّكُمْ كُنْتُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرُزِقْتُمْ كَمَا يُرْزَقُ الطَّيْرُ تَغْدُو خِمَاصًا وَتَرُوحُ بِطَانًا",
    english: "If you were to rely upon Allah with the reliance He is due, you would be provided for as the birds are provided for — they go out hungry in the morning and return full in the evening.",
    source: "Sunan al-Tirmidhī 2344 · Graded Ṣaḥīḥ",
    category: "trust",
    themes: ["provision"],
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2516",
    type: "hadith",
    arabic: "اعْقِلْهَا وَتَوَكَّلْ",
    english: "Tie it and rely upon Allah.",
    source: "Sunan al-Tirmidhī 2517 · Graded Ḥasan",
    category: "trust",
    editorialStatus: "published",
    scholarNotes: "Said to a man who asked whether to tie his camel or simply trust in Allah.",
  },
  {
    id: "h:muslim:2664",
    type: "hadith",
    arabic: "احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللَّهِ وَلاَ تَعْجِزْ",
    english: "Be keen on what benefits you, seek help from Allah, and do not give up.",
    source: "Ṣaḥīḥ Muslim 2664",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2664b",
    type: "hadith",
    arabic: "وَإِنْ أَصَابَكَ شَىْءٌ فَلاَ تَقُلْ لَوْ أَنِّي فَعَلْتُ كَانَ كَذَا وَكَذَا وَلَكِنْ قُلْ قَدَرُ اللَّهِ وَمَا شَاءَ فَعَلَ",
    english: "If something befalls you, do not say 'If only I had done such-and-such.' Rather say: 'It is the decree of Allah, and what He wills, He does.'",
    source: "Ṣaḥīḥ Muslim 2664",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "h:tirmidhi:2516b",
    type: "hadith",
    arabic: "وَاعْلَمْ أَنَّ الأُمَّةَ لَوِ اجْتَمَعَتْ عَلَى أَنْ يَنْفَعُوكَ بِشَىْءٍ لَمْ يَنْفَعُوكَ إِلاَّ بِشَىْءٍ قَدْ كَتَبَهُ اللَّهُ لَكَ وَلَوِ اجْتَمَعُوا عَلَى أَنْ يَضُرُّوكَ بِشَىْءٍ لَمْ يَضُرُّوكَ إِلاَّ بِشَىْءٍ قَدْ كَتَبَهُ اللَّهُ عَلَيْكَ",
    english: "Know that if the entire nation were to gather to benefit you, they could not benefit you except with what Allah has already written for you. And if they were to gather to harm you, they could not harm you except with what Allah has already written against you.",
    source: "Sunan al-Tirmidhī 2516 · Graded Ṣaḥīḥ",
    category: "trust",
    editorialStatus: "published",
  },
  {
    id: "h:muslim:2577",
    type: "hadith",
    arabic: "يَا عِبَادِي إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلاَ تَظَالَمُوا",
    english: "O My servants, I have forbidden injustice for Myself and have made it forbidden among you, so do not wrong one another.",
    source: "Ṣaḥīḥ Muslim 2577",
    category: "trust",
    themes: ["mercy"],
    editorialStatus: "published",
    scholarNotes: "A ḥadīth qudsī — one of the most profound narrations on Allah's justice and mercy.",
  },
];
