"use client";

import { useMemo, useState } from "react";

/**
 * Read-only, serializable slice of a research-register record — passed from
 * the server component. Deliberately omits sourceUrls, usulAiResearchNotes,
 * gradingNotes, editorialNotes, and every approved* field: this workbench
 * never pre-fills a proposed decision from existing data, per "do not
 * invent reviewer decisions."
 */
export interface MdrWorkbenchRecord {
  internalId: string;
  sequenceNumber: number;
  openingArabicWords: string;
  fullArabicText: string;
  originalDocumentText: string;
  sourceDocumentAnnotations: string[];
  transcriptionStatus: string;
  sourceResearchStatus: string;
  contentClassification: string;
  morningSpecificStatus: string;
  primaryReference: string;
  narrator: string;
  hadithGrading: string;
  wordingMatchStatus: string;
  repetitionCount?: number;
  virtueOrRewardClaim: string;
  scholarlyDecision: string;
  editorialApproval: string;
  importStatus: string;
  isComposite: boolean;
  canImport: boolean;
  blockedReasons: string[];
}

/** Local-only draft state — never sent anywhere, never persisted across a reload. */
interface DraftDecision {
  scholarlyReviewer: string;
  scholarlyReviewerQualification: string;
  scholarlyReviewDate: string;
  scholarlyDecision: string;
  scholarlyNotes: string;
  approvedArabicText: string;
  approvedEnglishText: string;
  approvedSourceReference: string;
  approvedTiming: string;
  approvedRepetitionCount: string;
  approvedVirtueText: string;
  editorialReviewer: string;
  editorialApproval: string;
  editorialApprovalDate: string;
}

const EMPTY_DRAFT: DraftDecision = {
  scholarlyReviewer: "",
  scholarlyReviewerQualification: "",
  scholarlyReviewDate: "",
  scholarlyDecision: "pending",
  scholarlyNotes: "",
  approvedArabicText: "",
  approvedEnglishText: "",
  approvedSourceReference: "",
  approvedTiming: "",
  approvedRepetitionCount: "",
  approvedVirtueText: "",
  editorialReviewer: "",
  editorialApproval: "pending",
  editorialApprovalDate: "",
};

const SCHOLARLY_DECISION_OPTIONS = ["pending", "approved", "approved-with-corrections", "deferred", "rejected"];
const EDITORIAL_APPROVAL_OPTIONS = ["pending", "approved", "revision-required", "rejected"];

const labelClass = "font-[family-name:var(--font-utility)] text-xs font-medium uppercase tracking-widest text-[#0E3B2E]/60 block mb-1";
const inputClass = "w-full border border-[#0E3B2E]/20 bg-white px-2 py-1.5 text-sm font-[family-name:var(--font-body)] text-[#0E3B2E]";

function fieldRow(label: string, value: string, onChange: (v: string) => void, multiline = false) {
  return (
    <div>
      <label className={labelClass}>{label}</label>
      {multiline ? (
        <textarea className={inputClass} rows={3} value={value} onChange={(e) => onChange(e.target.value)} />
      ) : (
        <input className={inputClass} type="text" value={value} onChange={(e) => onChange(e.target.value)} />
      )}
    </div>
  );
}

function generateDecisionRecordMarkdown(record: MdrWorkbenchRecord, draft: DraftDecision): string {
  return `# MDR Scholarly Decision Record — ${record.internalId} (DRAFT, not yet finalised)

## 1. Identification
- MDR ID: ${record.internalId}
- Decision date: ${draft.scholarlyReviewDate || "(not set)"}

## 2. Worksheets relied upon
(attach completed worksheet references here)

## 5. Exact approved wording
- Protected originalDocumentText/fullArabicText (unchanged, for reference):
  ${record.fullArabicText}
- Proposed approved publication wording:
  ${draft.approvedArabicText || "(same as protected text)"}

## 6. Approved source reference
${draft.approvedSourceReference || "(not set)"}

## 7. Grading scope
- Approved grading term(s): ${record.hadithGrading || "(not set)"}

## 8. Timing
- Proposed timing: ${draft.approvedTiming || "(not set)"}

## 9. Repetition
- Proposed repetition count: ${draft.approvedRepetitionCount || "(not set)"}

## 10. Virtue/reward
- Proposed virtue text: ${draft.approvedVirtueText || "(none)"}

## 14. Second-review confirmation
- Primary reviewer: ${draft.scholarlyReviewer || "(not set)"} (${draft.scholarlyReviewerQualification || "qualification not set"})
- Editorial reviewer: ${draft.editorialReviewer || "(not set)"}

## 15. Import recommendation
- Recommended scholarlyDecision: ${draft.scholarlyDecision}
- Recommended editorialApproval: ${draft.editorialApproval}
- Notes: ${draft.scholarlyNotes || "(none)"}

---
THIS IS A DRAFT GENERATED BY THE MDR REVIEW WORKBENCH. It is not binding, not saved, and not a
substitute for a completed MDR Scholarly Decision Record reviewed by a second reviewer and
transcribed into the register via a separate, explicitly-approved commit.
`;
}

export function MdrReviewWorkbench({ records }: { records: MdrWorkbenchRecord[] }) {
  const [selectedId, setSelectedId] = useState(records[0]?.internalId ?? "");
  const [drafts, setDrafts] = useState<Record<string, DraftDecision>>({});

  const selected = useMemo(() => records.find((r) => r.internalId === selectedId), [records, selectedId]);
  const draft = drafts[selectedId] ?? EMPTY_DRAFT;

  function updateDraft(patch: Partial<DraftDecision>) {
    setDrafts((prev) => ({ ...prev, [selectedId]: { ...(prev[selectedId] ?? EMPTY_DRAFT), ...patch } }));
  }

  if (!selected) return null;

  const markdown = generateDecisionRecordMarkdown(selected, draft);

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-[220px_1fr]">
      <nav aria-label="MDR records" className="border border-[#0E3B2E]/10 max-h-[70vh] overflow-y-auto">
        <ul className="divide-y divide-[#0E3B2E]/10">
          {records.map((r) => (
            <li key={r.internalId}>
              <button
                type="button"
                onClick={() => setSelectedId(r.internalId)}
                aria-current={r.internalId === selectedId}
                className={`w-full text-left px-3 py-2 text-sm font-[family-name:var(--font-utility)] ${
                  r.internalId === selectedId ? "bg-[#0E3B2E] text-white" : "text-[#0E3B2E] hover:bg-[#0E3B2E]/5"
                }`}
              >
                {r.internalId}
                {r.isComposite && <span className="ml-1 opacity-70">·composite</span>}
              </button>
            </li>
          ))}
        </ul>
      </nav>

      <div className="space-y-6">
        <section aria-labelledby="protected-text-heading" className="border border-[#0E3B2E]/20 p-4">
          <h2 id="protected-text-heading" className="font-[family-name:var(--font-utility)] text-xs font-medium uppercase tracking-widest text-[#0E3B2E]/60 mb-2">
            Protected transcription (read-only — {selected.internalId})
          </h2>
          <p dir="rtl" lang="ar" className="text-lg leading-relaxed text-[#0E3B2E] mb-2" style={{ userSelect: "text" }}>
            {selected.fullArabicText}
          </p>
          <dl className="text-xs text-[#0E3B2E]/70 grid grid-cols-2 gap-x-4 gap-y-1">
            <dt className="font-medium">Transcription status</dt>
            <dd>{selected.transcriptionStatus}</dd>
            <dt className="font-medium">Source research status</dt>
            <dd>{selected.sourceResearchStatus}</dd>
            <dt className="font-medium">Classification</dt>
            <dd>{selected.contentClassification}</dd>
            <dt className="font-medium">Morning-specific status</dt>
            <dd>{selected.morningSpecificStatus}</dd>
            <dt className="font-medium">Primary reference (research)</dt>
            <dd className="col-span-1 break-words">{selected.primaryReference || "—"}</dd>
            <dt className="font-medium">Hadith grading (research)</dt>
            <dd>{selected.hadithGrading || "—"}</dd>
            <dt className="font-medium">Wording match status</dt>
            <dd>{selected.wordingMatchStatus}</dd>
            <dt className="font-medium">Current scholarlyDecision</dt>
            <dd>{selected.scholarlyDecision}</dd>
            <dt className="font-medium">Current editorialApproval</dt>
            <dd>{selected.editorialApproval}</dd>
            <dt className="font-medium">Current importStatus</dt>
            <dd>{selected.importStatus}</dd>
          </dl>
        </section>

        <section aria-labelledby="gate-status-heading" className="border border-[#0E3B2E]/20 p-4">
          <h2 id="gate-status-heading" className="font-[family-name:var(--font-utility)] text-xs font-medium uppercase tracking-widest text-[#0E3B2E]/60 mb-2">
            Live import-gate status
          </h2>
          <p className="text-sm mb-2">
            {selected.canImport ? "canImport: true" : `canImport: false (${selected.blockedReasons.length} blocker(s))`}
          </p>
          {!selected.canImport && (
            <ul className="text-xs text-[#0E3B2E]/70 list-disc pl-4 space-y-0.5">
              {selected.blockedReasons.map((reason) => (
                <li key={reason}>{reason}</li>
              ))}
            </ul>
          )}
        </section>

        <section aria-labelledby="draft-heading" className="border border-[#0E3B2E]/20 p-4">
          <h2 id="draft-heading" className="font-[family-name:var(--font-utility)] text-xs font-medium uppercase tracking-widest text-[#0E3B2E]/60 mb-3">
            Draft proposed decision (not saved — local to this browser tab only)
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {fieldRow("Reviewer name", draft.scholarlyReviewer, (v) => updateDraft({ scholarlyReviewer: v }))}
            {fieldRow("Reviewer qualification", draft.scholarlyReviewerQualification, (v) => updateDraft({ scholarlyReviewerQualification: v }))}
            {fieldRow("Review date (YYYY-MM-DD)", draft.scholarlyReviewDate, (v) => updateDraft({ scholarlyReviewDate: v }))}
            <div>
              <label className={labelClass}>Scholarly decision</label>
              <select className={inputClass} value={draft.scholarlyDecision} onChange={(e) => updateDraft({ scholarlyDecision: e.target.value })}>
                {SCHOLARLY_DECISION_OPTIONS.map((opt) => (
                  <option key={opt} value={opt}>{opt}</option>
                ))}
              </select>
            </div>
          </div>
          <div className="mt-3">{fieldRow("Scholarly notes", draft.scholarlyNotes, (v) => updateDraft({ scholarlyNotes: v }), true)}</div>
          <div className="mt-3">{fieldRow("Proposed approved Arabic text", draft.approvedArabicText, (v) => updateDraft({ approvedArabicText: v }), true)}</div>
          <div className="mt-3">{fieldRow("Proposed approved English text", draft.approvedEnglishText, (v) => updateDraft({ approvedEnglishText: v }), true)}</div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
            {fieldRow("Approved source reference", draft.approvedSourceReference, (v) => updateDraft({ approvedSourceReference: v }))}
            {fieldRow("Approved timing", draft.approvedTiming, (v) => updateDraft({ approvedTiming: v }))}
            {fieldRow("Approved repetition count", draft.approvedRepetitionCount, (v) => updateDraft({ approvedRepetitionCount: v }))}
          </div>
          <div className="mt-3">{fieldRow("Proposed approved virtue/reward text", draft.approvedVirtueText, (v) => updateDraft({ approvedVirtueText: v }), true)}</div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
            {fieldRow("Editorial reviewer", draft.editorialReviewer, (v) => updateDraft({ editorialReviewer: v }))}
            {fieldRow("Editorial approval date (YYYY-MM-DD)", draft.editorialApprovalDate, (v) => updateDraft({ editorialApprovalDate: v }))}
            <div>
              <label className={labelClass}>Editorial approval</label>
              <select className={inputClass} value={draft.editorialApproval} onChange={(e) => updateDraft({ editorialApproval: e.target.value })}>
                {EDITORIAL_APPROVAL_OPTIONS.map((opt) => (
                  <option key={opt} value={opt}>{opt}</option>
                ))}
              </select>
            </div>
          </div>
        </section>

        <section aria-labelledby="markdown-heading" className="border border-[#0E3B2E]/20 p-4">
          <h2 id="markdown-heading" className="font-[family-name:var(--font-utility)] text-xs font-medium uppercase tracking-widest text-[#0E3B2E]/60 mb-2">
            Generated decision-record draft (copy into a real decision record file)
          </h2>
          <textarea readOnly className="w-full h-64 border border-[#0E3B2E]/20 bg-[#0E3B2E]/5 p-2 text-xs font-mono" value={markdown} />
        </section>
      </div>
    </div>
  );
}
